### ISSUE TITLE
Support Free/Shared plans

### ISSUE THREAD

**Issue by ramijarrar** [fractal-code/meteor-azure#1]
Deployment fails while installing Meteor due to quota restrictions:

``` log
tar: .meteor/packages/meteor-tool/1.4.1_1/mt-os.windows.x86_32/isopackets: Cannot mkdir: No space left on device
tar: .meteor/packages/meteor-tool/1.4.1_1/mt-os.windows.x86_32/isopackets/ddp/npm/node_modules/meteor/babel-compiler/node_modules/core-js/library/modules/es6.number.is-nan.js: Cannot open: No such file or directory
```

The only real solution to this would be native support (i.e pre-installation) on App Service.

**Comment by jycouet** [comment]
I have the same issue
What plan should be the minimum one?

**Comment by ramijarrar** [comment]
Due to quota restrictions you will need to use the Basic plan or higher - as documented in the prerequisites section.

After the first deploy, you could potentially downgrade to Free/Shared and continue running the app without any issues (since dependencies are cached) but there are no guarantees you'll be able to push updates reliably.

Besides, the Free/Shared offerings are restricted to 5/35 max concurrent connections, and you will really only appreciate App Service with multiple instances (to enable AutoScale, zero-downtime deploy, high availability, etc.)

It's also worth noting that unlike many PAAS offerings you are actually getting Dedicated VMs on Basic+ so you could host multiple apps on the same App Service.

**Comment by ramijarrar** [comment]
This is now supported in v2 of project, which performs all compilation locally.

See full announcement [here](https://forums.meteor.com/t/meteor-azure-2-0-supports-local-bundling-brand-new-docs/37266).
