### ISSUE TITLE
How to configure "App Settings"?

### ISSUE THREAD

**Issue by nwabdou85** [fractal-code/meteor-azure#10]
after have deplyed may react-meteor app, I get this error on http://elkoufa.azurewebsites.net/.

any one can explain me what's happens and how to fix it, please??

alos, I can't figure out where to set up all this bellow

Following App Settings:
SCM_COMMAND_IDLE_TIMEOUT - 3600
MONGO_URL - (MongoDB connection string)
MONGO_OPLOG_URL - (Optional: Recommended with multiple instances)
ROOT_URL - http://{sitename}.azurewebsites.net or your custom domain if you've set that up
METEOR_SETTINGS - (Optional: e.g from your settings.json)
WEBSITE_NODE_DEFAULT_VERSION - (Node version bundled with your current Meteor release)
METEOR_AZURE_NPM_VERSION - (NPM version bundled with your current Meteor release)

Any help please.

Thank's

**Comment by ramijarrar** [comment]
Assuming you have already followed the [steps](https://azure.microsoft.com/en-us/documentation/articles/app-service-continuous-deployment) to configure a deployment source, just add them in the portal under the "Application Settings" tab:

![screen shot 2016-11-14 at 12 29 31 pm](https://cloud.githubusercontent.com/assets/9661116/20250774/78c6de5c-aa66-11e6-999d-121b44a2bd20.png)

Then trigger a rebuild (in the "Deployment options" tab) and it should work correctly.

**Comment by nwabdou85** [comment]
@ramijarrar by default I ve something starting by WEBSITE_NODE_DEFAULT_VERSION ...

Should I replace it by what are in the image ?

**Comment by nwabdou85** [comment]
@ramijarrar  thank's for help, I still ve the error : You do not have permission to view this directory or page.

how can I fix it please?

**Comment by ramijarrar** [comment]
Please paste your deployment log.

**Comment by nwabdou85** [comment]
this one : Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\home\site\repository" -o "D:\home\site\deployments\tools" --node --sitePath "D:\home\site\repository"').

**Comment by ramijarrar** [comment]
It doesn't look like you have the script installed at all.

Please check that you have followed the setup instructions in the README (root directory should contain the `.deployment file` and `.config/azure` directory)

**Comment by nwabdou85** [comment]
in the root I ve script directory which cinains .deployment file and  and .config/azure directory

**Comment by nwabdou85** [comment]
and my main.js file is in root in server directory

**Comment by ramijarrar** [comment]
Okay, so where you went wrong: you need to copy the _contents_ of the script directory rather than the directory itself.

In other words, your file structure should look like this:

```
server/main.js
.config/azure
.deployment
```

If that isn't completely clear, consider taking a look at the [example](https://github.com/talos-code/meteor-azure-example) repo.

**Comment by nwabdou85** [comment]
Thank's, it's fixed for now, but still display nothing but this line : import '/imports/startup/server/index.js';
look at [http://elkoufa.azurewebsites.net/](http://elkoufa.azurewebsites.net/); is it normal?

**Comment by nwabdou85** [comment]
knowon that it's a react-meteor app, if that can help you

**Comment by nwabdou85** [comment]
and the only thing I've on main.js is this line :  import '/imports/startup/server/index.js';

**Comment by ramijarrar** [comment]
Does your app run locally? Do you have a deployment log (under the "Deployment options" tab in the portal)

**Comment by nwabdou85** [comment]
yes yes it run locally, and I ve deployment log inside Deployment options ( soory to be late, I've some probleme  with internt)

**Comment by ramijarrar** [comment]
Can you paste it?

**Comment by nwabdou85** [comment]
for now, it displays this one 
`
Command: bash .config/azure/deploy.sh
Invalid start-up command "meteor run" in package.json. Please use the format "node <script relative path>".
Looking for app.js/server.js under site root.
Missing server.js/app.js files, web.config is not generated
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 7.0.0, 7.1.0.
Selected node.js version 4.6.1. Use package.json file to choose a different version.
Selected npm version 2.15.9
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
meteor-azure: Setting NPM version
D:\local\AppData\npm\npm -> D:\local\AppData\npm\node_modules\npm\bin\npm-cli.js
npm@3.10.9 D:\local\AppData\npm\node_modules\npm
3.10.9
meteor-azure: Installing Meteor
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  3  155M    3 5343k    0     0  3195k      0  0:00:49  0:00:01  0:00:48 5343k
  7  155M    7 11.1M    0     0  4269k      0  0:00:37  0:00:02  0:00:35 5703k
 10  155M   10 16.9M    0     0  4740k      0  0:00:33  0:00:03  0:00:30 5802k
 15  155M   15 23.6M    0     0  5188k      0  0:00:30  0:00:04  0:00:26 6059k
 19  155M   19 29.5M    0     0  5339k      0  0:00:29  0:00:05  0:00:24 6057k
 22  155M   22 35.0M    0     0  5378k      0  0:00:29  0:00:06  0:00:23 6108k
 25  155M   25 40.2M    0     0  5376k      0  0:00:29  0:00:07  0:00:22 5968k
 29  155M   29 45.5M    0     0  5383k      0  0:00:29  0:00:08  0:00:21 5856k
 33  155M   33 51.5M    0     0  5462k      0  0:00:29  0:00:09  0:00:20 5718k
 37  155M   37 57.8M    0     0  5553k      0  0:00:28  0:00:10  0:00:18 5795k
 41  155M   41 63.9M    0     0  5612k      0  0:00:28  0:00:11  0:00:17 5923k
 44  155M   44 69.6M    0     0  5627k      0  0:00:28  0:00:12  0:00:16 6012k
 48  155M   48 75.4M    0     0  5652k      0  0:00:28  0:00:13  0:00:15 6118k
 53  155M   53 82.5M    0     0  5762k      0  0:00:27  0:00:14  0:00:13 6342k
 57  155M   57 88.9M    0     0  5811k      0  0:00:27  0:00:15  0:00:12 6361k
 60  155M   60 94.7M    0     0  5821k      0  0:00:27  0:00:16  0:00:11 6310k
 62  155M   62 96.9M    0     0  5615k      0  0:00:28  0:00:17  0:00:11 5584k
 65  155M   65  102M    0     0  5634k      0  0:00:28  0:00:18  0:00:10 5584k
 70  155M   70  109M    0     0  5712k      0  0:00:27  0:00:19  0:00:08 5564k
 74  155M   74  115M    0     0  5719k      0  0:00:27  0:00:20  0:00:07 5430k
 77  155M   77  121M    0     0  5727k      0  0:00:27  0:00:21  0:00:06 5414k
 81  155M   81  126M    0     0  5726k      0  0:00:27  0:00:22  0:00:05 6121k
 83  155M   83  130M    0     0  5637k      0  0:00:28  0:00:23  0:00:05 5648k
 86  155M   86  134M    0     0  5564k      0  0:00:28  0:00:24  0:00:04 4982k
 89  155M   89  139M    0     0  5571k      0  0:00:28  0:00:25  0:00:03 4960k
 93  155M   93  145M    0     0  5568k      0  0:00:28  0:00:26  0:00:02 4880k
 97  155M   97  151M    0     0  5592k      0  0:00:28  0:00:27  0:00:01 4982k
100  155M  100  155M    0     0  5623k      0  0:00:28  0:00:28 --:--:-- 5557k
meteor-azure: Building app
$ROOT_URL, if specified, must be an URL.
cp: cannot create regular file 'D:\local\LocalAppData\meteor-azure\bundle': No such file or directory
meteor-azure: Deploying bundle
.config/azure/deploy.sh: line 138: cd: D:\local\LocalAppData/meteor-azure: No such file or directory
meteor-azure: Finished successfully.`

**Comment by nwabdou85** [comment]
please check this link,I paste all the log https://codepaste.net/tkcowo

**Comment by ramijarrar** [comment]
You are missing the ROOT_URL setting...

**Comment by nwabdou85** [comment]
Can you explain more please or give me a link showing how to set it ??

**Comment by ramijarrar** [comment]
Under "App Settings" you need to add "ROOT_URL" (as documented in the README)

**Comment by nwabdou85** [comment]
Let me redo that , deploy it and tell the result , thank's

**Comment by ramijarrar** [comment]
Make sure you specify the full URL (i.e include the protocol)

**Comment by nwabdou85** [comment]
I ll do , thank's

**Comment by nwabdou85** [comment]
I'm sorry, it does not dispaly anthing for now, and this the log https://codepaste.net/q8hky8

**Comment by nwabdou85** [comment]
for now, its ok but it does display any thing and throw and error on browser : Failed to load resource: the server responded with a status of 404 (Not Found);

Ps: link for log https://codepaste.net/o1jny5
link to my json file https://codepaste.net/8pyai9
link to my web.config https://codepaste.net/m7xc1w
the entrey point is server/main.js in the root of project

Hop all this can help you 
Thank's

**Comment by nwabdou85** [comment]
@ramijarrar did you find how to fix it, please?

**Comment by ramijarrar** [comment]
Can you provide a screenshot of your "General settings" and "App settings" (both available under the "Application settings" tab in the portal)

**Comment by nwabdou85** [comment]
![Uploading portal.azure.com.jpg…]()
![Uploading portal.azure.com (1).jpg…]()
![Uploading portal.azure.com (2).jpg…]()

**Comment by nwabdou85** [comment]
[url=https://postimg.org/image/tlh7gc8nx/][img]https://s14.postimg.org/tlh7gc8nx/portal_azure_com.jpg[/img][/url]

[url=https://postimg.org/image/3r7eqk8nx/][img]https://s14.postimg.org/3r7eqk8nx/portal_azure_com_1.jpg[/img][/url]

[url=https://postimg.org/image/jdyo3xmfx/][img]https://s14.postimg.org/jdyo3xmfx/portal_azure_com_2.jpg[/img][/url]


[url=https://postimage.org/index.php?lang=french]hebergeur d image[/url]

**Comment by nwabdou85** [comment]
I paste the link of the screenshos here: 
https://postimg.org/image/tlh7gc8nx/
https://postimg.org/image/3r7eqk8nx/
https://postimg.org/image/jdyo3xmfx/

**Comment by nwabdou85** [comment]
@ramijarrar  and the browser, this is what I find: Failed to load resource: the server responded with a status of 404 (Not Found).

**Comment by nwabdou85** [comment]
One more thing,  in you json example the script was:start :meteor run,  but in log in portal  does not except it and demand something  like this :script : node path;

**Comment by ramijarrar** [comment]
Get rid of the "/" at the end of ROOT_URL and rebuild.

Don't worry about the "start" command because that is automatically corrected during the build process.

**Comment by nwabdou85** [comment]
@ramijarrar  same things ;(

**Comment by ramijarrar** [comment]
It's hard for me to say anything conclusive without meaningful diagnostics,

You'll need to create a simple reproduction (or temporarily provide read access to the repo if you are comfortable with that).

**Comment by nwabdou85** [comment]
can you give me your email, please? to give read access

**Comment by ramijarrar** [comment]
Can you do it through github?

**Comment by nwabdou85** [comment]
no, it's on bibucket

**Comment by ramijarrar** [comment]
Okay, use rami@talos.email

**Comment by nwabdou85** [comment]
it's done, you have an invitation in your box

**Comment by nwabdou85** [comment]
@ramijarrar  did finsd something??

**Comment by ramijarrar** [comment]
Will take a look at tonight (feel free to remove access now)

**Comment by nwabdou85** [comment]
cool, I'am waiting for you tonight,

**Comment by nwabdou85** [comment]
@ramijarrar  any idea to fix it?

**Comment by ramijarrar** [comment]
It deployed fine to my test server @ https://meteor-azure.azurewebsites.net

**Comment by nwabdou85** [comment]
@ramijarrar  cool, but it does not show anything, the same problem with me, this is what I see when i click on the link you gave me https://postimg.org/image/s5gmjtwcn/; did you see anything on your browser?

**Comment by nwabdou85** [comment]
@ramijarrar the same code works great on heroku :https://elkoufa.herokuapp.com/

**Comment by ramijarrar** [comment]
Looks like an app specific bug to me (I am not able to run it properly on my machine either)

**Comment by nwabdou85** [comment]
I deploy a test app on azure but it's same  error,  I think it has to do with configuration,  in log deployment I noticed that :"active":false,  that make sense to you?

**Comment by ramijarrar** [comment]
Continuing the discussion on the Meteor forums: you'll need to add me to the repo again to be able to test the new version.

**Comment by nwabdou85** [comment]
@ramijarrar it's done

**Comment by nwabdou85** [comment]
let me know if you receveived the invitation in your inbox, thank's

**Comment by ramijarrar** [comment]
Haven't received anything yet.

**Comment by nwabdou85** [comment]
and now?

**Comment by nwabdou85** [comment]
this is additional log, may be help you to understand what's going on http://paste.ofcode.org/VVGYBc5yAJRRty5VYFH2Xs
http://paste.ofcode.org/7NTuffRHHTDKZgGqxMFw2a

**Comment by ramijarrar** [comment]
Just received it - will take a look later tonight.

**Comment by nwabdou85** [comment]
if you ve juste one minute to look at those logs and show if you can help me with, that's ll be great and save me a lot of time.
http://paste.ofcode.org/VVGYBc5yAJRRty5VYFH2Xs
http://paste.ofcode.org/7NTuffRHHTDKZgGqxMFw2a

**Comment by ramijarrar** [comment]
Still getting the same error when trying to run the app locally:

```
/Users/moe-talos/koufa_complet/.meteor/local/build/programs/server/app/app.js:1871
import {Mongo} from 'meteor/mongo';
^^^^^^   
   
SyntaxError: Unexpected reserved word
     at Object.exports.runInThisContext (vm.js:53:16)
     at /Users/moe-talos/koufa_complet/.meteor/local/build/programs/server/boot.js:289:30
     at Array.forEach (native)
     at Function._.each._.forEach (/Users/moe-talos/.meteor/packages/meteor-tool/.1.4.2_3.p44j98++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
     at /Users/moe-talos/koufa_complet/.meteor/local/build/programs/server/boot.js:128:5
     at /Users/moe-talos/koufa_complet/.meteor/local/build/programs/server/boot.js:344:5
     at Function.run (/Users/moe-talos/koufa_complet/.meteor/local/build/programs/server/profile.js:480:12
     at /Users/moe-talos/koufa_complet/.meteor/local/build/programs/server/boot.js:343:11

=> Exited with code: 1                        
=> Your application is crashing. Waiting for file change.
```

**Comment by nwabdou85** [comment]
@ramijarrar  it should be ok for now, I added .babelrc file; and you ve still access to repo; let me know if you can run it on local? Thank's

**Comment by nwabdou85** [comment]
@ramijarrar did you win run it ??

this is my laste log http://paste.ofcode.org/35kuGUxMxY6Adki5YyKYJWz

**Comment by nwabdou85** [comment]
@ramijarrar  ??

**Comment by ramijarrar** [comment]
The latest version is still crashing with the same error.

I'm not able to look into this any further if the app doesn't start on my local machine (using the ```meteor``` command).

Nothing I have seen so far points to any issue with the deployment.

**Comment by nwabdou85** [comment]
wich os do you use ?

**Comment by ramijarrar** [comment]
macOS Sierra

**Comment by nwabdou85** [comment]
it's weired , I use a transpiler babel, escamp script?

which meteor version do you use?
did you use a clone of my project in local and does not work ?

**Comment by nwabdou85** [comment]
And you does not matter, can you have a call on what's app or skip ?

**Comment by ramijarrar** [comment]
Not sure what you mean, the version of Meteor is app-specific.

I'm running straight off a clone of your project.

**Comment by ramijarrar** [comment]
> And you does not matter, can you have a call on what's app or skip ?

This is an open source project - that kind of support is completely out-of-scope (we are not being paid to maintain this).

**Comment by nwabdou85** [comment]
I understand you, may be with call ( shared screen) the things goes fatser and thank's you for your help.

**Comment by nwabdou85** [comment]
@ramijarrar I add ecamscript as suggested in stackover flow but I don't if you ve still an error or no!!

however, can you suggest me what to do based on this log http://paste.ofcode.org/3mT5hi5Duw5Bym4f9wnbwE ? please

Thank's

**Comment by ramijarrar** [comment]
Are you able to start the app on your machine using the ```meteor``` command?

**Comment by nwabdou85** [comment]
it works without problem in my local machine; I ve no problem in local at any time (Linux); also on herokuapp works

**Comment by nwabdou85** [comment]
my only problem is when I try to upload it to azure

**Comment by nwabdou85** [comment]
Please, can you ensure me that it works on your machine ?

**Comment by nwabdou85** [comment]
now that I use an adequat version of node, i can deploy it on azure, but still the page does not display anything http://paste.ofcode.org/hABG3uR7t8uhSDB6Abgf2v; is there something to do with settings?

**Comment by ramijarrar** [comment]
Right now the deployment is irrelevant. 

I think I might have an idea about what is going on, can you try the following:

1) Open the "Downloads" tab on Bitbucket (under "NAVIGATION")

2) Download and unzip the master branch then navigate to that directory in the terminal

3) Run ```meteor npm install```

4) Run ```meteor```

Then paste the output of steps 3 & 4

**Comment by nwabdou85** [comment]
the output of 3 is : KOUFA@ /home/abdou/Desktop/koufa_complet
└── bcrypt-nodejs@0.0.3 
for 4: is coming

**Comment by nwabdou85** [comment]
the output of step n4 is here http://paste.ofcode.org/Qb4QwJpNVqTRXsYfKsNyeY

**Comment by ramijarrar** [comment]
What OS are you running in your dev environment?

**Comment by nwabdou85** [comment]
OS: ubuntu 14.04 LTS
are they diffrents form the the output you got ?

**Comment by nwabdou85** [comment]
and I use node v5.11.1, npm v3.8.6 in my machine

Ps: may be this can help http://paste.ofcode.org/BfvQffTDUQyGcWXtrR7S7W

**Comment by nwabdou85** [comment]
any news, insights ?? have you run it on your machine without error?

**Comment by ramijarrar** [comment]
First of all, Node v5.11.1 is incompatible with Meteor. You need to make sure you're using the same version bundled with your release (as documented in the setup instructions).  This doesn't matter locally, because ```meteor npm``` & ```meteor node``` use the correct versions internally.

Unfortunately, following those same steps (which confirm the codebase is consistent) I am still getting the error above.

It looks like your app has cross-platform compatibility issues - I have access to an Ubuntu machine at home which I can use to confirm this later tonight.

If you have access to Windows/macOS that would probably be the easiest way to start debugging.

**Comment by nwabdou85** [comment]
I ll check it on windows , 
let me know what you get when you try it on ubuntu, please.
in package.json I use node 4.6.1(which is compatible) not V5.11.1

**Comment by ramijarrar** [comment]
Just tested on an Ubuntu machine: the app starts with no errors.

**Comment by nwabdou85** [comment]
@ramijarrar  so where is the problem ?
METEOR@1.4.2.1 is supported on azure?

**Comment by ramijarrar** [comment]
The app is built on a Windows VM (so the problem is cross-platform compatibility)

**Comment by nwabdou85** [comment]
So, what you can suggest me to fix it if I can ?

**Comment by ramijarrar** [comment]
It's hard for me to say anything conclusive without a deeper look at your app's internals (which is out-of-scope for the support we can provide)

Generally speaking though, these kinds of problems usually tend to be the result of archaic dependencies (e.g see https://github.com/talos-code/meteor-azure/issues/3)

**Comment by nwabdou85** [comment]
Thank's

**Comment by nwabdou85** [comment]
@ramijarrar  excuse me one more time, 
thoses links form log stream (Kudu > Tools > Log Stream) make sense for you ?? 

https://paste.ofcode.org/uQbudxDfQwJWBXXMMLpjf4
https://paste.ofcode.org/RCRzeS62dcsJ3q94c7ccqG
https://paste.ofcode.org/n2XFM85yhtKDcWMhYXkVXt
https://paste.ofcode.org/RwwA8JCjXWbhdP6JJmqsAZ

Thank's

**Comment by ramijarrar** [comment]
Looks like the app is deploying correctly, but doesn't start due to this error:

```cmd
Error: key emails.address must not contain '.'
    at Object.Future.wait (D:\home\site\wwwroot\programs\server\node_modules\fibers\future.js:449:15)
    at MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:828:10)
    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:685:20)
    at setupUsersCollection (packages/accounts-base/accounts_server.js:1492:9)
    at new AccountsServer (packages/accounts-base/accounts_server.js:51:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages\modules-runtime.js:181:9)
    at require (packages\modules-runtime.js:106:16)
    at D:\home\site\wwwroot\programs\server\packages\accounts-base.js:1972:15
    at D:\home\site\wwwroot\programs\server\packages\accounts-base.js:1983:3
```

**Comment by nwabdou85** [comment]
@ramijarrar  yes, it does; any idea on how to fixe it ? thank's

**Comment by stockcj** [comment]
I have the same issue: "key emails.address must not contain '.'"

@nwabdou85 - did you ever get to the bottom of what was causing this?

**Comment by nwabdou85** [comment]
@stockcj no :(
