### ISSUE TITLE
main.js added to url with force ssl rule

### ISSUE THREAD

**Issue by ManuelDeLeon** [fractal-code/meteor-azure#11]
Using the latest script. When I add the following force SSL rule, it adds `/main.js` to the url when I navigate to the root of the site and I get the error `too many redirects`.

```
<rule name="Redirect to HTTPS" stopProcessing="true">
  <match url="(.*)" />
  <conditions>
    <add input="{HTTPS}" pattern="^OFF$" />
  </conditions>
   <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" redirectType="Permanent" />
</rule>
```

Any clues?

**Comment by ramijarrar** [comment]
Can you confirm that you're not using the ```force-ssl``` package (check .versions for implicit dependencies)?

**Comment by ManuelDeLeon** [comment]
I'll double check.

**Comment by ManuelDeLeon** [comment]
Nope, no `force-ssl` references anywhere.

**Comment by ramijarrar** [comment]
Okay - are you making any other adjustments to the standard web.config?

**Comment by ManuelDeLeon** [comment]
Nope

**Comment by ramijarrar** [comment]
Your web.config should look like this: https://raw.githubusercontent.com/talos-code/meteor-azure-example/master/.config/azure/web.config

And your ROOT_URL need to be written with the ```https``` protocol.

**Comment by ramijarrar** [comment]
I suspect you may have added the rule at the end (which would explain the routing to ```/main.js```).

**Comment by ManuelDeLeon** [comment]
Yes, I added it to the end. I'll test it right when I get home.

It should be in the Readme =)

**Comment by ManuelDeLeon** [comment]
I copied that web.config and it deployed correctly but now the site is down: `redirected you too many times.`

**Comment by ramijarrar** [comment]
Can you try visiting the URL using "https" directly? Does that work properly?

**Comment by ManuelDeLeon** [comment]
Same message

**Comment by ramijarrar** [comment]
Can you try in a different browser?

**Comment by ManuelDeLeon** [comment]
tried it with Chrome and Edge

**Comment by ramijarrar** [comment]
Still not working?

**Comment by ManuelDeLeon** [comment]
Nope

**Comment by ramijarrar** [comment]
Can you provide the URL? (you can DM me on Meteor forums if you prefer)

**Comment by ManuelDeLeon** [comment]
Let me deploy it again.

**Comment by ManuelDeLeon** [comment]
Sorry for the late reply but deployments take more than 20mins so testing is really slow. It has to be a caching/dns issue with this laptop. I tried it on another computer and the site works fine now that the rule is on top.

Thanks for the help.

**Comment by ramijarrar** [comment]
I will add a link in the README to the example web.config (with force https rule)

**Comment by ramijarrar** [comment]
I made a few improvements to the 'force https' instructions based on this issue, let me know if you think there is room for any further clarification.
