### ISSUE TITLE
Add support for nested meteor root

### ISSUE THREAD

**Issue by arshbucks** [fractal-code/meteor-azure#14]
Do you know how to modify this setup if there is no "main.js" in the root directory?
For example, if using the recommended app structure here: [https://guide.meteor.com/structure.html](https://guide.meteor.com/structure.html#example-app-structure)

(perhaps in the config file you would add "client/main.js" and/or "server/main.js"? Would you need both? )

Many thanks

**Comment by ramijarrar** [comment]
Not sure where you got the idea this was a requirement?

**Comment by ramijarrar** [comment]
(The entry-point you refer to is generated during the build process and does not depend on any particular app structure)

**Comment by arshbucks** [comment]
I'm not getting a proper deployment - see below "no such file or directory".
Can't really tell what it's due to, but seemed like it is not recognizing an actual meteor app - perhaps because the main.js file is not available.

@ D:\home\site\repository
+-- babel-runtime@6.20.0 
| +-- core-js@2.4.1 
| `-- regenerator-runtime@0.10.1 
`-- meteor-node-stubs@0.2.4 
  +-- asn1.js@4.9.0 
  +-- assert@1.4.1 
  +-- Base64@0.2.1 
  +-- base64-js@1.2.0 
  +-- bn.js@4.11.6 
  +-- brorand@1.0.6 
  +-- browserify-aes@1.0.6 
  +-- browserify-cipher@1.0.0 
  +-- browserify-des@1.0.0 
  +-- browserify-rsa@4.0.1 
  +-- browserify-sign@4.0.0 
  +-- browserify-zlib@0.1.4 
  +-- buffer@4.9.1 
  +-- buffer-shims@1.0.0 
  +-- buffer-xor@1.0.3 
  +-- cipher-base@1.0.3 
  +-- console-browserify@1.1.0 
  +-- constants-browserify@1.0.0 
  +-- core-util-is@1.0.2 
  +-- create-ecdh@4.0.0 
  +-- create-hash@1.1.2 
  +-- create-hmac@1.1.4 
  +-- crypto-browserify@3.11.0 
  +-- date-now@0.1.4 
  +-- des.js@1.0.0 
  +-- diffie-hellman@5.0.2 
  +-- domain-browser@1.1.7 
  +-- elliptic@6.3.2 
  +-- events@1.1.1 
  +-- evp_bytestokey@1.0.0 
  +-- hash.js@1.0.3 
  +-- http-browserify@1.7.0 
  +-- https-browserify@0.0.1 
  +-- ieee754@1.1.8 
  +-- indexof@0.0.1 
  +-- inherits@2.0.1 
  +-- isarray@1.0.0 
  +-- miller-rabin@4.0.0 
  +-- minimalistic-assert@1.0.0 
  +-- os-browserify@0.2.1 
  +-- pako@0.2.9 
  +-- parse-asn1@5.0.0 
  +-- path-browserify@0.0.0 
  +-- pbkdf2@3.0.9 
  +-- process@0.11.9 
  +-- process-nextick-args@1.0.7 
  +-- public-encrypt@4.0.0 
  +-- punycode@1.4.1 
  +-- querystring@0.2.0 
  +-- querystring-es3@0.2.1 
  +-- randombytes@2.0.3 
  +-- readable-stream@2.2.1 
  +-- ripemd160@1.0.1 
  +-- sha.js@2.4.8 
  +-- stream-browserify@2.0.1 
  +-- string_decoder@0.10.31 
  +-- timers-browserify@1.4.2 
  +-- tty-browserify@0.0.0 
  +-- url@0.11.0 
  | `-- punycode@1.3.2 
  +-- util@0.10.3 
  +-- util-deprecate@1.0.2 
  `-- vm-browserify@0.0.4 

build: You're not in a Meteor project directory.

To create a new Meteor project:
  meteor create <project name>
For example:
  meteor create myapp

For more help, see 'meteor --help'.
cp: cannot create regular file 'D:\local\LocalAppData\meteor-azure\bundle': No such file or directory
meteor-azure: Setting Node runtime
.config/azure/deploy.sh: line 130: cd: D:\local\LocalAppData\meteor-azure\bundle: No such file or directory
meteor-azure: Deploying bundle
.config/azure/deploy.sh: line 135: cd: D:\local\LocalAppData\meteor-azure: No such file or directory
meteor-azure: Finished successfully

**Comment by ramijarrar** [comment]
The script assumes your ```.meteor``` directory is at the root of the repository. Do you have a different file structure?

**Comment by arshbucks** [comment]
ah, no it is not. 
I can change the deploy.sh Lines 74 and 121 to prefix ".meteor" with the path - and it should work then?
If that doesn't work I'll try moving it to the root...Thanks

**Comment by ramijarrar** [comment]
That should work, but I think it makes sense to add proper support through an Application Setting (something like ```METEOR_AZURE_ROOT```).

**Comment by arshbucks** [comment]
That's a great idea. Thanks again for your responsiveness & attentiveness

**Comment by ramijarrar** [comment]
Just released v1.3.0 which adds support for this (I've also made the [example project](https://github.com/talos-code/meteor-azure-example) a nested Meteor application)

Please let me know if you have any further issues.
