### ISSUE TITLE
Problem with mocked file name (alanning:roles)

### ISSUE THREAD

**Issue by tgoldenberg** [fractal-code/meteor-azure#15]
I'm having errors with the deployment script. I was having difficulties integrating with Github (nevermind that I'm not the Github admin at work so I have to bug my boss everytime to configure it), so I used local Git option. 

This seems to work fine, except I get the error:
```
remote: Updating branch 'master'.
remote: Deployment failed
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://WEBAPP_ADDRESS.scm.azurewebsites.net:443/WEBAPP_NAME.git
   1dc5c74..d71b1fd  master -> master
```
Also, in Azure, I get this:

![screen shot 2016-12-14 at 4 21 38 pm](https://cloud.githubusercontent.com/assets/10930134/21202891/4977c664-c21e-11e6-8a5c-167c684ee4d1.png)
 simple statement

I assume this is because Azure doesn't recognize "something:something" as a valid folder name? However, it's hard to fix this, since I need a mock of the `alanning:roles` package for my Jest tests to work.

Really curious if you have any suggestions. Thanks!

Before opening an issue, please check if a similar one already exists or has been closed before.

If you are reporting a bug, please be sure to include the following:

- Script version is Version: 1.0.8

**Comment by tgoldenberg** [comment]
UPDATE: 

So I was able to avoid the filename error by using the `moduleNameMapper` config option for Jest.

Here's a piece of my package.json:

```
"jest": {
    "moduleNameMapper": {
      "^meteor/meteor": "<rootDir>/.tests/meteor/meteor.js",
      "^meteor/alanning:roles": "<rootDir>/.tests/meteor/roles.js"
    },
    "modulePathIgnorePatterns": [
      "meteor-dev-bundles"
    ]
  },
```

I'm not sure if I'm able to get this running smoothly all the way, but it looks like this error is solved.

**Comment by ramijarrar** [comment]
Great that you were able to work around this. 

Since Azure doesn't expose the push mechanism, any solution we could provide would realistically have to run locally anyways (the build fails before the script is even executed).

Going to hold off any further debugging for now, please let me know if you run into anything else.
