### ISSUE TITLE
"npm failed" error

### ISSUE THREAD

**Issue by arshbucks** [fractal-code/meteor-azure#18]
This may be related to one of the earlier issues w/ NPM, but have been unable to figure it out. Please let me know if you can derive any useful actions from this error message?

`An error has occurred during web site deployment.
npm failed
npm WARN meteor-dev-bundle@0.0.0 No description\r\nnpm WARN meteor-dev-bundle@0.0.0 No repository field.\r\nnpm WARN meteor-dev-bundle@0.0.0 No license field.\r\nnpm ERR! Windows_NT 6.2.9200\r\nnpm ERR! argv "D:\\home\\meteor-azure\\nvm\\v4.6.2\\node.exe" "D:\\home\\meteor-azure\\nvm\\v4.6.2\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"\r\nnpm ERR! node v4.6.2\r\nnpm ERR! npm  v3.10.9\r\nnpm ERR! path D:\home\site\wwwroot\programs\server\node_modules\fibers\bin\win32-ia32-46\fibers.node\r\nnpm ERR! code EPERM\r\nnpm ERR! errno -4048\r\nnpm ERR! syscall unlink\r\n\r\nnpm ERR! Error: EPERM: operation not permitted, unlink 'D:\home\site\wwwroot\programs\server\node_modules\fibers\bin\win32-ia32-46\fibers.node'\r\nnpm ERR!     at Error (native)\r\nnpm ERR!  { [Error: EPERM: operation not permitted, unlink 'D:\home\site\wwwroot\programs\server\node_modules\fibers\bin\win32-ia32-46\fibers.node']\r\nnpm ERR!   errno: -4048,\r\nnpm ERR!   code: 'EPERM',\r\nnpm ERR!   syscall: 'unlink',\r\nnpm ERR!   path: 'D:\\home\\site\\wwwroot\\programs\\server\\node_modules\\fibers\\bin\\win32-ia32-46\\fibers.node',\r\nnpm ERR!   parent: 'meteor-dev-bundle' }\r\nnpm ERR! \r\nnpm ERR! Please try running this command again as root/Administrator.\r\n\r\nnpm ERR! Please include the following file with any support request:\r\nnpm ERR!     D:\home\site\wwwroot\programs\server\npm-debug.log\r\nD:\Program Files (x86)\SiteExtensions\Kudu\59.51212.2600\bin\Scripts\starter.cmd bash .config/azure/deploy.sh`

Not-so-funny part is it worked perfectly on the previous deploy (the only change i made was 2 words in 1 HTML file), and the same codebase (dev branch) works on another deployment slot.

**Comment by ramijarrar** [comment]
Can you provide the full deployment log?

**Comment by arshbucks** [comment]
Sorry - I disconnected my git deployment to try & reset the deployment process, so don't have full log. But the above was at the end of the log & looked like it was a concatenation of all previous messages.

I am redeploying right now -- if it fails again (4th time) I will post the full log in the morning (~6 hrs from now)

**Comment by ramijarrar** [comment]
Can you also check that you are using the latest version (1.4.4) of the script?

**Comment by arshbucks** [comment]
good call - my script is a month old. 
I will try with 1.4.4 soon and let you know if issue persists. Thanks

**Comment by ramijarrar** [comment]
Yep - we've made some pretty major improvements under the hood and significantly cut down build times (which will be noticeable on subsequent deploys)

**Comment by arshbucks** [comment]
Nice - good to know & thanks for that!

The redeploy (by disconnecting the git repo + reconnecting, not simply clicking redploy/resync) worked, with script 1.2.2. But i will also upgrade to 1.4.4. Thanks again.

**Comment by arshbucks** [comment]
FYI - still get similar deployment errors at random. In this case the only change I made from the previous deployed commit was adding the "HTTPS" block rule back into your new 1.4.4 web.config file.

For example, this failed deploy ran for 48396 seconds (that's not a typo) - and produced just the following error log:

`Command: bash .config/azure/deploy.sh
meteor-azure: Setting Node version
Version 4.6.2 is already installed.
meteor-azure: Now using Node v4.6.2 (32-bit)
meteor-azure: Setting NPM version
meteor-azure: Now using NPM v3.10.9
meteor-azure: Installing NPM dependencies
meteor-azure: Building app
Thread was being aborted.
Thread was being aborted.`

Not reopening as I don't think this is an issue w/ the deployment script - but rather an Azure compatibility/versioning issue with Node/NPM

**Comment by ramijarrar** [comment]
Random errors are not okay :)

If this is still happening with the latest version - please open a new issue with your full deployment log and relevant context (it's hard to tell what's going on right now without line by line timestamps/status codes)

**Comment by arshbucks** [comment]
Ok, will do next time - I resynced my repo & it successfully deployed this time... will let you know when it happens again.
