### ISSUE TITLE
Underscore CLI npm install fails

### ISSUE THREAD

**Issue by dick** [fractal-code/meteor-azure#2]
I'm trying my first deploy and running into issues. I think I've followed the directions so far, Meteor is at 1.4.1.1, default Node.js version in Azure set to 4.5. The deployment seems to be failing when npm install attempts to compile underscore-cli: 

Here are my logs:
Dicks-MBP:petropi dick$ git push azure master
Counting objects: 2879, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2733/2733), done.
Writing objects: 100% (2879/2879), 3.10 MiB | 959.00 KiB/s, done.
Total 2879 (delta 806), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: ..............................................
remote: Updating submodules.
remote: Preparing deployment for commit id 'aa771c2b5c'.
remote: Running custom deployment command...
remote: Running deployment command...
remote: ..
remote: D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\underscore -> D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\node_modules\underscore-cli\bin\underscore
remote: 
remote: > msgpack@1.0.2 install D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\node_modules\underscore-cli\node_modules\msgpack
remote: > node-gyp rebuild
remote: 
remote: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
remote:   objectc.c
remote: ......\deps\msgpack\objectc.c(24): fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory [D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\node_modules\underscore-cli\node_modules\msgpack\build\deps\msgpack\libmsgpack.vcxproj]
remote:   unpack.c
remote:   vrefbuffer.c
remote:   zone.c
remote:   version.c
remote:   win_delay_load_hook.cc
remote: gyp ERR! build error 
remote: D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin
remote: `-- underscore-cli@0.2.19 
remote: 
remote: gyp ERR! stack Error:`msbuild` failed with exit code: 1
remote: gyp ERR! stack     at ChildProcess.onExit (D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
remote: gyp ERR! stack     at emitTwo (events.js:87:13)
remote: gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
remote: gyp ERR! System Windows_NT 6.2.9200
remote: gyp ERR! command "D:\local\LocalAppData\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\node.exe" "D:\local\LocalAppData\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
remote: gyp ERR! cwd D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\node_modules\underscore-cli\node_modules\msgpack
remote: gyp ERR! node -v v4.5.0
remote: gyp ERR! node-gyp -v v3.4.0
remote: gyp ERR! not ok 
remote: ..........................
remote: D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
remote:       throw error;
remote:       ^
remote: 
remote: Error: ENOENT: no such file or directory, open 'D:\local\Temp\mt-d7rzn0\os\packages\anti_i18n.js'
remote:     at Error (native)
remote: .config/azure/deploy.sh: line 92: cd: D:\local\Temp\8d3de559eb491ca\bundle\programs\server: Not a directory
remote: .config/azure/deploy.sh: line 93: underscore: command not found
remote: The system cannot find the file specified.
remote: Handling node.js deployment.
remote: KuduSync.NET from: 'D:\local\Temp\8d3de559eb491ca\bundle' to: 'D:\home\site\wwwroot'
remote: Error: The directory name is invalid.
remote: An error has occurred during web site deployment.
remote: 
remote: Kudu Sync failed
remote: 
remote: Error - Changes committed to remote repository but deployment to website failed.
To ...  master -> master

**Comment by ramijarrar** [comment]
Can you paste your application settings? Is this your first build? 

I've noticed similar errors with underscore-cli in the past, but they were mostly harmless.

**Comment by dick** [comment]
[Here's a screenshot of my App Settings](https://www.dropbox.com/s/vwmh2uicstm3l4y/Screenshot%202016-09-16%2020.43.39.png?dl=0)

Am I correct that the application settings only need to be set in Azure, or do they also need to be in a settings.json file?

I'm not sure what you mean by whether this is my first build. I had a couple of unsuccessful deploys before this one and have had no successful builds. Should I start fresh with a new Azure app?

**Comment by ramijarrar** [comment]
Settings look fine to me. Were the other unsuccessful deploys using this script?

**Comment by dick** [comment]
Yes.

**Comment by dick** [comment]
One question that came up -- does this script expect node_modules to be included or ignored from the git commit? I think I had it ignored on my first attempt to deploy and then added node_modules back in.

**Comment by ramijarrar** [comment]
You definitely shouldn't be committing node_modules, what does the file structure of your app look like (we expect .meteor is at the top-level)?

**Comment by dick** [comment]
[Here is the file structure](https://www.dropbox.com/s/qxe1f3mhdx3gjg1/Screenshot%202016-09-17%2013.26.43.png?dl=0). Settings.json is excluded and from an old deployment to Galaxy.

I tried again with a fresh Azure app service and node_modules properly excluded from the first try, but it still failed. Here are is the log:

remote: D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\underscore -> D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\node_modules\underscore-cli\bin\underscore
remote: 
remote: > msgpack@1.0.2 install D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\node_modules\underscore-cli\node_modules\msgpack
remote: > node-gyp rebuild
remote: 
remote: .....
remote: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
remote:   objectc.c
remote: ......\deps\msgpack\objectc.c(24): fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory [D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\node_modules\underscore-cli\node_modules\msgpack\build\deps\msgpack\libmsgpack.vcxproj]
remote:   unpack.c
remote:   vrefbuffer.c
remote:   zone.c
remote:   version.c
remote:   win_delay_load_hook.cc
remote: gyp ERR! build error 
remote: gyp ERR! stack Error: `msbuild` failed with exit code: 1
remote: gyp ERR! stack     at ChildProcess.onExit (D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
remote: gyp ERR! stack     at emitTwo (events.js:87:13)
remote: gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
remote: gyp ERR! System Windows_NT 6.2.9200
remote: gyp ERR! command "D:\local\LocalAppData\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\node.exe" "D:\local\LocalAppData\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
remote: gyp ERR! cwd D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin\node_modules\underscore-cli\node_modules\msgpack
remote: gyp ERR! node -v v4.5.0
remote: gyp ERR! node-gyp -v v3.4.0
remote: gyp ERR! not ok 
remote: D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\bin
remote: `-- underscore-cli@0.2.19 
remote:   +-- coffee-script@1.10.0 
remote:   +-- commander@1.0.5 
remote:   |`-- keypress@0.1.0 
remote:   +-- JSONSelect@0.4.0 
remote:   +-- underscore@1.8.3 
remote:   `-- underscore.string@3.2.3 
remote: 
remote: ..........................
remote: 
remote: > bcrypt@0.8.7 install D:\home\site\repository\node_modules\bcrypt
remote: > node-gyp rebuild
remote: 
remote: 
remote: D:\home\site\repository\node_modules\bcrypt>if not defined npm_config_node_gyp (node "D:\local\LocalAppData\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
remote: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
remote:   blowfish.cc
remote:   bcrypt.cc
remote: ..\src\bcrypt.cc(232): warning C4267: '=': conversion from 'size_t' to 'unsigned char', possible loss of data [D:\home\site\repository\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
remote:   bcrypt_node.cc
remote:   win_delay_load_hook.cc
remote:      Creating library D:\home\site\repository\node_modules\bcrypt\build\Release\bcrypt_lib.lib and object D:\home\site\repository\node_modules\bcrypt\build\Release\bcrypt_lib.exp
remote:   Generating code
remote: .........................................................
remote:   Finished generating code
remote:   bcrypt_lib.vcxproj -> D:\home\site\repository\node_modules\bcrypt\build\Release\\bcrypt_lib.node
remote: petropi@1.0.0 D:\home\site\repository
remote: +-- azure-iot-common@1.0.14 
remote: |`-- crypto@0.0.3 
remote: +-- azure-iothub@1.0.16 
remote: | +-- azure-iot-amqp-base@1.0.15 
remote: | | +-- amqp10@3.2.5 
remote: | | | +-- bl@1.1.2 
remote: | | | | `-- readable-stream@2.0.6 
remote: | | | |   +-- core-util-is@1.0.2 
remote: | | | |   +-- inherits@2.0.3 
remote: | | | |   +-- isarray@1.0.0 
remote: | | | |   +-- process-nextick-args@1.0.7 
remote: | | | |   +-- string_decoder@0.10.31 
remote: | | | |`-- util-deprecate@1.0.2 
remote: | | | +-- buffer-builder@0.2.0 
remote: | | | +-- lodash@4.15.0 
remote: | | | +-- node-amqp-encoder@0.0.2 
remote: | | | +-- node-int64@0.4.0 
remote: | | | `-- stately.js@1.3.0 
remote: | | +-- amqp10-transport-ws@0.0.4 
remote: | | |`-- nodejs-websocket@1.7.0 
remote: | | `-- debug@2.2.0 
remote: | |`-- ms@0.7.1 
remote: | +-- azure-iot-http-base@1.0.15 
remote: | `-- uuid@2.0.2 
remote: +-- bcrypt@0.8.7 
remote: | +-- bindings@1.2.1 
remote: |`-- nan@2.3.5 
remote: +-- bluebird@3.4.6 
remote: +-- chart.js@2.2.2 
remote: | +-- chartjs-color@2.0.0 
remote: | | +-- chartjs-color-string@0.4.0 
remote: | | | `-- color-name@1.1.1 
remote: | |`-- color-convert@0.5.3 
remote: | `-- moment@2.15.0 
remote:`-- prettify@0.1.7 
remote:   +-- js-prettify@1.4.0 
remote:   | +-- config-chain@1.1.10 
remote:   | | +-- ini@1.3.4 
remote:   | | `-- proto-list@1.2.4 
remote:   | +-- mkdirp@0.3.5 
remote:   |`-- nopt@2.1.2 
remote:   |   `-- abbrev@1.0.9 
remote:`-- lodash@1.3.1 
remote: 
remote: ..............................................................................................
remote: D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
remote:       throw error;
remote:       ^
remote: 
remote: Error: ENOENT: no such file or directory, open 'D:\local\Temp\mt-wvue37\os\packages\anti_i18n.js'
remote:     at Error (native)
remote: .config/azure/deploy.sh: line 92: cd: D:\local\Temp\8d3df28bb0be961\bundle\programs\server: Not a directory
remote: .config/azure/deploy.sh: line 93: underscore: command not found
remote: The system cannot find the file specified.
remote: Handling node.js deployment.
remote: KuduSync.NET from: 'D:\local\Temp\8d3df28bb0be961\bundle' to: 'D:\home\site\wwwroot'
remote: Error: The directory name is invalid.
remote: An error has occurred during web site deployment.
remote: 
remote: Kudu Sync failed
remote: 
remote: Error - Changes committed to remote repository but deployment to website failed.

**Comment by ramijarrar** [comment]
I'm working on a fix for this. Check back in a few hours.

**Comment by ramijarrar** [comment]
Just pushed some architectural changes which should significantly improve reliability. I ended up removing the dependency on Underscore CLI altogether (which was causing a number of unrelated headaches as well).

Let me know when you get a chance to test it & please open a separate thread for further issues.
