### ISSUE TITLE
Configure as a Build and Release in Visual Studio Team Services

### ISSUE THREAD

**Issue by cjmiska** [fractal-code/meteor-azure#24]
Is it possible to alter the .deployment script so it can be run as a build in VSTS, which produces a deployment package?

You can run sh from VSTS, so was wondering if it's possible to set-up the build there and then release to Azure, rather than getting Azure to fetch everything and then run the build and deployment.

Thanks

**Comment by ramijarrar** [comment]
v2 has been rewritten as an npm CLI to support local bundling (pushing the tarball to Azure and then running a very simple deployment script for server initialization). This should provide all the benefits of the approach you have described, without restricting people to VS.

Closing this for now. Feel free to re-open or file a new issue if you have further questions/ideas.

**Comment by jycouet** [comment]
Hi :)
First, thx for this repo.
In VSTS if we use a hosted build agent, Meteor is not installed. Could we add this at the begining of meteor-azure?

Thx for the info

**Comment by ramijarrar** [comment]
What would be the advantage to running it in VSTS over the local compilation approach we have now? Also, is there a reason why this couldn't be added in an external script which wraps meteor-azure?

**Comment by jycouet** [comment]
I think that I will do a bigger script calling meteor-azure inside yes :)
The idea of running this in VSTS is to test and deploy on a PR merged (it's to do my CI)

**Comment by junlouiegonzales** [comment]
I think it would be nice if there is a option for build only

like this.
meteor-azure --build-only

So this will become the process in our CI/ CD
- Build the meteor app using meteor-azure with build only option
- After the build, compress and publish the artifact
- And in our release pipeline we can use the "Azure App Service Deploy"

What you think? :)

**Comment by ramijarrar** [comment]
@junlouiegonzales Please open a new issue for this.
