### ISSUE TITLE
Changes pushsed from Continious Deployment not coming through even with METEOR_AZURE_NOCACHE = 1

### ISSUE THREAD

**Issue by DanceParty** [fractal-code/meteor-azure#25]
When I do not have METEOR_AZURE_NOCACHE set to 1, the continuous deployment works find and says it is successful but the changes I made are not reflected on the website.

When I set METEOR_AZURE_NOCACHE to 1, the continuous deployment fails and the website stops working.

I have pretty much limited it down to this line in the scrip

```
if [[ -v METEOR_AZURE_NOCACHE && -d D:/home/meteor-azure ]]; then
  echo meteor-azure: Clearing cache
  rm -rf D:/home/meteor-azure
fi
if [ ! -d D:/home/meteor-azure ]; then
  mkdir D:/home/meteor-azure
fi
```

and when I actually run `rm -rf D:/home/meteor-azure` in the KUDU console, it gives me file path too long errors.

Any help is appreciated.

**Comment by ramijarrar** [comment]
We've just released v2 of the project which takes a completely different approach that addresses many of these sorts of issues people have faced with server-side bundling (as well as other significant improvements to UX and build speeds). See full announcement [here](https://forums.meteor.com/t/meteor-azure-2-0-supports-local-bundling-brand-new-docs/37266).

Please try again and open a new issue for any further problems/questions. Closing this.
