### ISSUE TITLE
Failed running deployment command

### ISSUE THREAD

**Issue by adammoisa** [fractal-code/meteor-azure#27]
<img width="777" alt="google chrome_2017-05-01 09 44 19" src="https://cloud.githubusercontent.com/assets/6547161/25580992/d99bcc68-2e52-11e7-8376-bf3cc484bbb3.png">
Hi, it looks like it's almost there but I get this error:

```
Command: bash .config/azure/deploy.sh
meteor-azure: Installing NVM
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   594    0   594    0     0   1224      0 --:--:-- --:--:-- --:--:--  1224

  8 2409k    8  202k    0     0   172k      0  0:00:13  0:00:01  0:00:12  172k
100 2409k  100 2409k    0     0  1214k      0  0:00:01  0:00:01 --:--:-- 2714k
Archive:  nvm-noinstall.zip
  inflating: nvm/LICENSE             
  inflating: nvm/elevate.cmd         
  inflating: nvm/elevate.vbs         
  inflating: nvm/install.cmd         
  inflating: nvm/nvm.exe             
meteor-azure: Setting Node version
Downloading node.js version 0.10.36 (32-bit)... Complete
Creating D:/home/meteor-azure/nvm\temp

Downloading npm version 1.4.28... Complete
Installing npm v1.4.28...

Installation complete. If you want to use this version, type

nvm use 0.10.36
meteor-azure: Now using Node v0.10.36 (32-bit)
meteor-azure: Setting NPM version
D:\home\meteor-azure\nvm\v0.10.36\npm -> D:\home\meteor-azure\nvm\v0.10.36\node_modules\npm\bin\npm-cli.js
npm@4.5.0 D:\home\meteor-azure\nvm\v0.10.36\node_modules\npm
meteor-azure: Now using NPM v4.5.0
meteor-azure: Installing JSON tool
Thread was being aborted.
npm 
Thread was being aborted.
```

Can you help? I think I have all the right app settings.

**Comment by ramijarrar** [comment]
What version of Meteor are you using?

**Comment by adammoisa** [comment]
1.4.3.1.

Also, is it absolutely required to have a basic account? I am on a free trial with Azure credit. Looked around the account and actually I can't even figure out how to upgrade to basic plan.

**Comment by ramijarrar** [comment]
No issue with being on a free trial account, just make sure the app service is on the basic plan or higher.

**Comment by ramijarrar** [comment]
Based on your Meteor version, it looks like you've misconfigured the Node/NPM versions.

Make sure the values for METEOR_AZURE_NODE_VERSION and METEOR_AZURE_NPM_VERSION match those you get when running ```meteor node --version``` & ```meteor npm --version``` locally.

**Comment by adammoisa** [comment]
Ok I will try this and let you know!

**Comment by adammoisa** [comment]
Hi I updated the app settings to match but still have an issue. I've also validated I'm on standard which is above basic so no prob there.

<img width="361" alt="screen shot 2017-05-03 at 8 30 06 am" src="https://cloud.githubusercontent.com/assets/6547161/25660553/caafbc1c-2fda-11e7-8433-b43844998bd2.png">

**Comment by varunkumar17** [comment]
Have similar issue

Command: bash .config/azure/deploy.sh
meteor-azure: Setting Node version
Version 8.0.0 is already installed.
meteor-azure: Now using Node v8.0.0 (32-bit)
meteor-azure: Setting NPM version
meteor-azure: Now using NPM v5.0.0
meteor-azure: Installing NPM dependencies
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
up to date in 3.794s
up to date in 3.045s
meteor-azure: Building app
'"D:\home\meteor-azure\.meteor\\packages\meteor-tool\1.5.0\mt-os.windows.x86_32\meteor.bat"' is not recognized as an internal or external command,
operable program or batch file.
meteor-azure: Setting Node runtime
.config/azure/deploy.sh: line 150: cd: D:\local\Temp\8d4ac22f73c0a6b\bundle: Not a directory
meteor-azure: Setting entry-point
.config/azure/deploy.sh: line 155: cd: D:\local\Temp\8d4ac22f73c0a6b\bundle\programs\server: Not a directory
meteor-azure: Deploying bundle
meteor-azure: Installing Meteor server
.config/azure/deploy.sh: line 169: cd: D:\home\site\wwwroot\programs\server: No such file or directory
up to date in 3.571s
meteor-azure: Finished successfully

**Comment by adammoisa** [comment]
@varunkumar17 ended up figuring it out and wrote a basic tutorial that hopefully will help you. Don't remember the specific issue otherwise, I'd just point it out right here. Pretty sure it had something to do with setting up endpoints. Anyway here's the walkthru:
https://medium.com/@adammoisa/how-to-deploy-a-meteor-app-to-an-azure-vm-with-mup-on-the-new-azure-interface-da49652a59d

**Comment by ramijarrar** [comment]
@adammoisa @varunkumar17 

We've just released v2 of the project, which takes a completely different approach that addresses many of these sorts of issues people have faced with server-side bundling (as well as other significant improvements to UX and build speeds). See full announcement [here](https://forums.meteor.com/t/meteor-azure-2-0-supports-local-bundling-brand-new-docs/37266).

Please file a new issue for any further problems/questions. Closing this.
