### ISSUE TITLE
Can it scale as part of the deployment process?

### ISSUE THREAD

**Issue by ManuelDeLeon** [fractal-code/meteor-azure#29]
Any chance v2 can scale up and out during deployment, and back down after? For example, to a configured value of up to Basic and out to 2 instances, then back to Shared (1 instance).

**Comment by ramijarrar** [comment]
v2 is now compatible with free/shared instances, so there's no longer any benefit to switching plans during deployment (just make sure you are aware of [service limits](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#app-service-limits) on bandwidth, concurrent connections, etc.).

Outside that context though: we've made the decision not to integrate administrative actions in the tool itself, given that functionality is already provided by the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/overview) (which is well documented and maintained).

Automating pre/post deployment tasks is straightforward with a simple bash script (we've taken care to ensure it exits on failure and reports the correct status code)

**Comment by ManuelDeLeon** [comment]
Cool, thanks.
