### ISSUE TITLE
Error with anti:i18n package

### ISSUE THREAD

**Issue by dick** [fractal-code/meteor-azure#3]
(Following #2)

I tried the updated code, but deployment still failed for me. Here are the logs:

remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '609b841e5f'.
remote: Running custom deployment command...
remote: Running deployment command...
remote: meteor-azure: Installing Meteor
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote: 
remote:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
remote:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
remote: 
remote:   0  143M    0  607k    0     0   732k      0  0:03:19 --:--:--  0:03:19  732k
remote:   5  143M    5 7503k    0     0  4102k      0  0:00:35  0:00:01  0:00:34 6896k
remote:  10  143M   10 14.3M    0     0  5208k      0  0:00:28  0:00:02  0:00:26 7064k
remote:  14  143M   14 20.3M    0     0  5432k      0  0:00:26  0:00:03  0:00:23 6730k
remote:  18  143M   18 26.6M    0     0  5645k      0  0:00:25  0:00:04  0:00:21 6664k
remote:  23  143M   23 33.3M    0     0  5860k      0  0:00:24  0:00:05  0:00:19 6710k
remote:  27  143M   27 39.3M    0     0  5901k      0  0:00:24  0:00:06  0:00:18 6560k
remote:  31  143M   31 45.5M    0     0  5963k      0  0:00:24  0:00:07  0:00:17 6390k
remote:  36  143M   36 52.1M    0     0  6049k      0  0:00:24  0:00:08  0:00:16 6521k
remote:  41  143M   41 58.7M    0     0  6122k      0  0:00:23  0:00:09  0:00:14 6582k
remote:  45  143M   45 64.6M    0     0  6113k      0  0:00:23  0:00:10  0:00:13 6409k
remote:  49  143M   49 71.3M    0     0  6175k      0  0:00:23  0:00:11  0:00:12 6550k
remote:  54  143M   54 77.8M    0     0  6212k      0  0:00:23  0:00:12  0:00:11 6601k
remote:  58  143M   58 84.0M    0     0  6226k      0  0:00:23  0:00:13  0:00:10 6540k
remote:  63  143M   63 90.5M    0     0  6251k      0  0:00:23  0:00:14  0:00:09 6505k
remote:  67  143M   67 96.2M    0     0  6227k      0  0:00:23  0:00:15  0:00:08 6473k
remote:  71  143M   71  102M    0     0  6252k      0  0:00:23  0:00:16  0:00:07 6435k
remote:  76  143M   76  109M    0     0  6305k      0  0:00:23  0:00:17  0:00:06 6544k
remote:  81  143M   81  116M    0     0  6314k      0  0:00:23  0:00:18  0:00:05 6556k
remote:  85  143M   85  121M    0     0  6284k      0  0:00:23  0:00:19  0:00:04 6384k
remote:  89  143M   89  128M    0     0  6301k      0  0:00:23  0:00:20  0:00:03 6537k
remote:  93  143M   93  134M    0     0  6289k      0  0:00:23  0:00:21  0:00:02 6411k
remote:  98  143M   98  140M    0     0  6294k      0  0:00:23  0:00:22  0:00:01 6256k
remote: 100  143M  100  143M    0     0  6302k      0  0:00:23  0:00:23 --:--:-- 6253k
remote: .............................................................................................................................................................................................
remote: meteor-azure: Building app
remote: ...............................................................
remote: D:\local\LocalAppData.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
remote:       throw error;
remote:       ^
remote: 
remote: Error: ENOENT: no such file or directory, open 'D:\local\Temp\mt-1uyhdac\os\packages\anti_i18n.js'
remote:     at Error (native)
remote: cp: cannot create regular file 'D:\local\Temp\8d3e09c6b98d7ad\output\bundle': No such file or directory
remote: Handling node.js deployment.
remote: KuduSync.NET from: 'D:\local\Temp\8d3e09c6b98d7ad\output\bundle' to: 'D:\home\site\wwwroot'
remote: Error: Could not find a part of the path 'D:\local\Temp\8d3e09c6b98d7ad\output\bundle'.
remote: An error has occurred during web site deployment.
remote: Kudu Sync failed
remote: 
remote: Error - Changes committed to remote repository but deployment to website failed.

**Comment by ramijarrar** [comment]
I was able to reproduce this by adding anti:i18n to the [example repo](https://github.com/talos-code/meteor-azure-example). 

These kinds of incompatibilities are not surprising given the age of the package (Windows support was added in Meteor v1.1, this hasn't been updated since pre-1.0 days).

Can you try again after removing anti:18n and confirm if there are still any errors?

**Comment by ramijarrar** [comment]
FYI, I took a closer look at the source code and it doesn't look like it would take very long to bring it up-to-date with the current patterns (i.e adopt modules, replace deprecated dependencies, etc.)

In the meantime, I forked it [here](https://github.com/talos-code/meteor-i18n) and updated the Meteor version (one-line fix, see [diff](https://github.com/talos-code/meteor-i18n/commit/76753736f005b2afbf1c7ded4b461b2c65d2c220)) to compile properly on Windows. You can install it with `meteor add talos:anti-i18n` - interface is the same so you shouldn't need to change any existing code.

**Comment by dick** [comment]
Getting rid of the login package that used anti-i18n fixed my issues. Thank you for the support!

**Comment by BrianJVarley** [comment]
Hi,

I notice this same error on `meteor run` command with `meteor v- 1.4.1.1`.
Looking at the above was there a fix identified for this `ENOENT error` by adding package `meteor add talos:anti-i18n` ?


This is my console error when running the application:

```
$ meteor run
[[[[[ C:\Users\barleyb\Documents\Projects\omo-progam-site ]]]]]

=> Started proxy.
=> A patch (Meteor 1.4.1.3) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
C:\Users\barleyb\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\barleyb\AppData\Local\Temp\mt-1hxzzkd\os\packages\meteorhacks_collection-utils.js'
    at Error (native)

```

**Comment by ramijarrar** [comment]
@BrianJVarley So are you getting that error after adding the patched version of the package?
