### ISSUE TITLE
Error/Stuck on Running server initialisation, polling for status...

### ISSUE THREAD

**Issue by ManuelDeLeon** [fractal-code/meteor-azure#32]
With --debug it gets stuck polling for status:

- Meteor version
1.5

- Package version (run `meteor-azure -v`)
2.0.2

- Command output with debug mode enabled
```
> meteor-azure --debug --settings settings.json --web-config .\.config\azure\web.config

info:    Authenticating with interactive login...
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code - to authenticate.
debug:   completed Azure authentication
info:    Updating Azure application settings
debug:   set environment variables
debug:   set Meteor settings
debug:   set Kudu deployment settings
debug:   set Node to v4.8.3
debug:   set NPM to v4.6.1
info:    Compiling application bundle
debug:   generate meteor build
debug:   add custom web config
debug:   create tarball
info:    Deploying bundle tarball
info:    Running server initialisation, polling for status...
```

Without the --debug flag it shows this error:

```
info:    Running server initialisation, polling for status...
error:   getaddrinfo ENOTFOUND viewmodel.scm.azurewebsites.net viewmodel.scm.azurewebsites.net:443
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ViewModel.org@ just-deploy: `meteor-azure --settings settings.json --web-config .\.config\azure\web.config`
npm ERR! Exit status 1
```

I don't know where the `scm` comes from. The site is `viewmodel.org` and `viewmodel.azurewebsites.net` redirects to it.

**Comment by ramijarrar** [comment]
The `scm` is for your [Kudu admin interface](https://github.com/projectkudu/kudu/wiki/Accessing-the-kudu-service), but that isn't part of the error. 

This looks like it might be DNS related (see https://github.com/nodejs/node/issues/5436 and https://github.com/nodejs/node/issues/7931), but I'm not too sure at this point. I've just pushed v2.0.4 which includes better error handling for the server initialization - can you try with that and paste the output?

**Comment by ManuelDeLeon** [comment]
`2.0.4` (with or without --debug) doesn't give me the chance to log in, it shows the login message and goes straight to an error:

```
> meteor-azure --debug --settings settings.json --web-config .\.config\azure\web.config

info:    Authenticating with interactive login...
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code - to authenticate.
error:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ViewModel.org@ just-deploy: `meteor-azure --debug --settings settings.json --web-config .\.config\azure\web.config`
npm ERR! Exit status 1
```

**Comment by ramijarrar** [comment]
Just released v2.0.5 which should fix the issue with interactive logins (was due to a [dependency conflict](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/137) which was only affecting local usage).

Can you try with that and let me know if any issues persist?

**Comment by ManuelDeLeon** [comment]
Still getting it:

```
> ViewModel.org@ deploy C:\MyFiles\Meteor\viewmodel.org
> npm run just-deploy

npm WARN invalid config loglevel="notice"

> ViewModel.org@ just-deploy C:\MyFiles\Meteor\viewmodel.org
> meteor-azure --debug --settings settings.json --web-config .\.config\azure\web.config

info:    Authenticating with interactive login...
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code - to authenticate.
error:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ViewModel.org@ just-deploy: `meteor-azure --debug --settings settings.json --web-config .\.config\azure\web.config`
npm ERR! Exit status 1
```

**Comment by ramijarrar** [comment]
Are you using shrinkwrap/yarn lock? You will need to refresh the dependency tree for the changes in 2.0.5 to work (or just use the package globally).

**Comment by ManuelDeLeon** [comment]
It's deploying now. I had to delete node_modules and yarn.lock file. Previously I just did a `yarn upgrade meteor-azure` and it seemed to have upgraded the version (it even updated package.json to the latest).

Thanks for the help and many thanks for this tool.

**Comment by ramijarrar** [comment]
No problem, this was actually a tricky one to address due to the issue coming from an implicit dependency version (otherwise running "yarn upgrade" should be adequate).

Glad it's working for you now.
