### ISSUE TITLE
ROOT_URL in 2 places

### ISSUE THREAD

**Issue by jycouet** [fractal-code/meteor-azure#37]
Hi, 

Now I have the ROOT_URL 2 times in my setting.json
```
{
  "meteor-azure": {
    "siteName": "",
    "resourceGroup": "",
    "subscriptionId": "",
    "tenantId": "",
    "deploymentCreds": {
      "username": "",
      "password": ""
    },
    "envVariables": {
      "ROOT_URL": "My Rout URL",
      "MONGO_URL": ""
    }
  },
  "runtime": {
    "meteorEnv": {},
    "DDP_DEFAULT_CONNECTION_URL": "",
    "ROOT_URL": "My Rout URL again :P"
  },
}
```

Do you have an idea to "merge" these two fields?
> ```Thx```

**Comment by ramijarrar** [comment]
You can use ``process.env.ROOT_URL`` to access the value directly, is that what you were after?

**Comment by jycouet** [comment]
Sorry about the question, actually, the "runtime" section is for https://github.com/Urigo/meteor-client-bundler
I wondered how to reuse the same parameter. 

I close the question since I did a mistake in meteor-client-bundler config anyway.
Yes, meteor-client-bundler is using `process.env.ROOT_URL` and not `runtime.ROOT_URL`

Thank you for your support
