### ISSUE TITLE
Clear password

### ISSUE THREAD

**Issue by jycouet** [fractal-code/meteor-azure#38]
Sorry, I have another question, you store and commit in your source code `deploymentCreds.password` ?
Is there a way to avoid it?

**Comment by ramijarrar** [comment]
If you prefer, you can load the config file from any path on your machine.

Ideally though, you should be storing it in your source code with encryption. Depending on your VCS, there are many tools that facilitate this (e.g we use [transcrypt](https://github.com/elasticdog/transcrypt) for Git).
