### ISSUE TITLE
How does Azure handle a failed instance?

### ISSUE THREAD

**Issue by guilhermedecampo** [fractal-code/meteor-azure#40]
Given the deployment was done correctly and you have your app running fine.

If one user action crash the meteor server for any reason what azure does?

What are your experience about this?

Thanks @ramijarrar.

**Comment by ramijarrar** [comment]
In the case of an application error, Azure will automatically reroute to a healthy instance (assuming you've provisioned another one).

In more advanced scenarios (e.g setting up regional failover or changing the load balancing method), you can [configure](https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-traffic-manager#web-apps-and-traffic-manager-profiles) Traffic Manager.

**Comment by guilhermedecampo** [comment]
It's just a matter of having 2 instances of the application? Do you have a documentation for that?
Found [this one](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/virtual-machines-windows/multi-vm)

**Comment by ramijarrar** [comment]
That page is for Azure VMs (which are much lower level), you can view the relevant documentation for App Service platform [here](https://docs.microsoft.com/en-us/azure/app-service-web/).

From https://stackoverflow.com/questions/30403214/does-an-azure-web-app-care-if-its-instances-are-healthy-unhealthy:

> Yes, Azure Web Apps monitors the health of the workers by making internal requests to it and verifying that they're healthy:
>
> However, we don't check status codes that the web app returns to user  requests (like 500, etc) since that could easily be an app specific issue rather than a problem with the machine.
>
> So the answer you're looking for is: We continuously test whether or not the instances (VMs) 
are healthy and take them down if they're not. However, those tests do not rely on error codes the customer's site returns.

**Comment by ramijarrar** [comment]
Also, for the application itself: we are running in [IISNode](https://github.com/azure/iisnode), which manages the Node process (this includes handling things like crashes, code updates, etc.).

**Comment by ramijarrar** [comment]
Closing this, please re-open if you have any further queries.
