### ISSUE TITLE
Fails with error at 'Authenticating with interactive login'

### ISSUE THREAD

**Issue by willrbc** [fractal-code/meteor-azure#42]
- Operating system macOs Sierra

- Meteor version : 1.4.4.1

- Package version 2.0.6

When deploying the script no longer waits for me to authenticate using the browser,  it immediately exits with errno1,  see below:

This only happens on one of my projects,  the other project with meteor 1.5.1 deploys fine.

 ```nfo:    Authenticating with interactive login...
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code DEXXPTHEW to authenticate.
error:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! floqo@1.0.0 deploy-azure: `meteor-azure --settings settings-beta.json`
npm ERR! Exit status 1```

**Comment by ramijarrar** [comment]
Can you confirm whether you're running from a local/global installation when this happens?

**Comment by willrbc** [comment]
It's running locally, although it is installed globally. I'm running it using an meteor npm run script configured in my package.json

**Comment by ramijarrar** [comment]
Can you confirm the output of ``meteor-azure -v`` from the local npm run script? (This was a known issue which we addressed in v2.0.5, so I suspect you may actually be on an older version in that project)

**Comment by willrbc** [comment]
It says 2.0.6, I will check through the 'getting started' again in the docs to make sure everything is set up correctly on the azure app,  in case I missed a step

**Comment by ramijarrar** [comment]
Can you try running ``npm ls async``  in the project directory and paste the output? 

Also, in the meantime you should be able to use the tool globally without any issues.

**Comment by willrbc** [comment]
```├─┬ intercom-client@2.8.5
│ └─┬ unirest@0.5.1
│   ├─┬ form-data@0.2.0
│   │ └── async@0.9.2
│   └─┬ request@2.74.0
│     └─┬ form-data@1.0.1
│       └── async@2.4.1
└─┬ meteor-azure@2.0.6
  ├── async@1.5.2
  ├─┬ ms-rest-azure@2.2.3
  │ ├─┬ adal-node@0.1.22
  │ │ └── async@0.9.2  deduped
  │ └── async@0.2.7
  └─┬ winston@2.3.1
    └── `async@1.0.0

**Comment by willrbc** [comment]
if I try to run it globally I get a totally different error,  not sure if this is an issue with y NPM installation

```/usr/local/lib/node_modules/meteor-azure/node_modules/tar/lib/pack.js:32
const EOF = Buffer.alloc(1024)
                   ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor-azure/node_modules/tar/lib/pack.js:32:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor-azure/node_modules/tar/lib/create.js:6:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by willrbc** [comment]
I have got it working globally, I just had to update Node.

**Comment by ramijarrar** [comment]
As of v2.0.7, you should no longer have any trouble using the package locally. 

Closing this, please re-open if the issue persists.
