### ISSUE TITLE
500 error when trying to access website

### ISSUE THREAD

**Issue by SammyIsra** [fractal-code/meteor-azure#5]
Hello all!

I am getting a 500 error when trying to access my Meteor website. Since the website works in localhost, I assume the error exists when publishing using meteor-azure. Script version and deployment log follow. 

Thank you!
- Error from server: `Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
- Script version 1.0.1
- Deployment log
  
  > ```
  > Command: bash .config/azure/deploy.sh
  > meteor-azure: Building app
  > Handling node.js deployment.
  > KuduSync.NET from: 'D:\local\LocalAppData\meteor-azure\bundle' to: 'D:\home\site\wwwroot'
  > Deleting file: '.gitignore'
  > Deleting file: 'package.json'
  > Copying file: '.node_version.txt'
  > Copying file: 'main.js'
  > Copying file: 'README'
  > Copying file: 'star.json'
  > Deleting file: '.meteor\.finished-upgraders'
  > Deleting file: '.meteor\.gitignore'
  > Deleting file: '.meteor\.id'
  > Deleting file: '.meteor\packages'
  > Deleting file: '.meteor\platforms'
  > Deleting file: '.meteor\release'
  > Deleting file: '.meteor\versions'
  > Deleting directory: '.meteor'
  > Deleting file: 'client\main.css'
  > Deleting file: 'client\main.html'
  > Deleting file: 'client\main.js'
  > Deleting directory: 'client'
  > Deleting file: 'imports\api\articles.js'
  > Deleting directory: 'imports\api'
  > Deleting file: 'imports\ui\article.html'
  > Deleting file: 'imports\ui\article.js'
  > Deleting file: 'imports\ui\body.html'
  > Deleting file: 'imports\ui\body.js'
  > Deleting file: 'imports\ui\footer.html'
  > Deleting file: 'imports\ui\footer.js'
  > Deleting file: 'imports\ui\header.html'
  > Deleting file: 'imports\ui\header.js'
  > Deleting directory: 'imports\ui'
  > Deleting directory: 'imports'
  > Deleting file: 'public\FlavoredNewsLogo.png'
  > Deleting file: 'public\gitgit.png'
  > Deleting directory: 'public'
  > Copying file: 'programs\server\boot-utils.js'
  > Copying file: 'programs\server\boot.js'
  > Copying file: 'programs\server\config.json'
  > Copying file: 'programs\server\mini-files.js'
  > Copying file: 'programs\server\npm-rebuild-args.js'
  > Copying file: 'programs\server\npm-rebuild.js'
  > Copying file: 'programs\server\npm-rebuilds.json'
  > Copying file: 'programs\server\npm-require.js'
  > Copying file: 'programs\server\npm-shrinkwrap.json'
  > Copying file: 'programs\server\package.json'
  > Copying file: 'programs\server\program.json'
  > Copying file: 'programs\server\server-json.js'
  > Copying file: 'programs\server\app\app.js'
  > Copying file: 'programs\server\app\app.js.map'
  > Copying file: 'programs\server\assets\packages\boilerplate-generator\boilerplate_web.browser.html'
  > Copying file: 'programs\server\assets\packages\boilerplate-generator\boilerplate_web.cordova.html'
  > Omitting next output lines...
  > Processed 1776 files...
  > Processed 3814 files...
  > Processed 5639 files...
  > Processed 7317 files...
  > Invalid start-up command "meteor run" in package.json. Please use the format "node <script relative path>".
  > Looking for app.js/server.js under site root.
  > Missing server.js/app.js files, web.config is not generated
  > The package.json file does not specify node.js engine version constraints.
  > The node.js application will run with the default node.js version 4.4.7.
  > Selected npm version 2.15.8
  > meteor-azure: Installing JSON tool
  > D:\local\AppData\npm\json -> D:\local\AppData\npm\node_modules\json\lib\json.js
  > json@9.0.4 D:\local\AppData\npm\node_modules\json
  > meteor-azure: Preparing package.json
  > meteor-azure: Installing NPM packages
  > npm WARN package.json meteor-dev-bundle@0.0.0 No description
  > npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
  > npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  > npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
  > fibers@1.0.13 install D:\home\site\wwwroot\programs\server\node_modules\fibers
  > node build.js || nodejs build.js
  > `win32-ia32-v8-4.5` exists; testing
  > Binary is fine; exiting
  > amdefine@1.0.0 node_modules\amdefine
  > underscore@1.5.2 node_modules\underscore
  > meteor-promise@0.7.2 node_modules\meteor-promise
  > asap@2.0.5 node_modules\asap
  > semver@4.1.0 node_modules\semver
  > source-map-support@0.3.2 node_modules\source-map-support
  > source-map@0.1.32 node_modules\source-map
  > promise@7.1.1 node_modules\promise
  > fibers@1.0.13 node_modules\fibers
  > meteor-azure: Finished successfully.
  > ```

```
```

**Comment by ramijarrar** [comment]
What does your web.config look like?

**Comment by SammyIsra** [comment]
Just like the default one:

```

<?xml version="1.0" encoding="utf-8"?>
<!--
     This configuration file is required if iisnode is used to run node processes behind
     IIS or IIS Express.  For more information, visit:

     https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config
-->

<configuration>
  <system.webServer>
    <!-- Visit http://blogs.msdn.com/b/windowsazure/archive/2013/11/14/introduction-to-websockets-on-windows-azure-web-sites.aspx for more information on WebSocket support -->
    <webSocket enabled="false" />
    <handlers>
      <!-- Indicates that the main.js file is a node.js site to be handled by the iisnode module -->
      <add name="iisnode" path="main.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        <!-- Do not interfere with requests for node-inspector debugging -->
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^main.js\/debug[\/]?" />
        </rule>

        <!-- First we consider whether the incoming URL matches a physical file in the /public folder -->
        <rule name="StaticContent">
          <action type="Rewrite" url="public{REQUEST_URI}"/>
        </rule>

        <!-- All other URLs are mapped to the node.js site entry point -->
        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
          </conditions>
          <action type="Rewrite" url="main.js"/>
        </rule>
      </rules>
    </rewrite>

    <!-- 'bin' directory has no special meaning in node.js and apps can be placed in it -->
    <security>
      <requestFiltering>
        <hiddenSegments>
          <remove segment="bin"/>
        </hiddenSegments>
      </requestFiltering>
    </security>

    <!-- Make sure error responses are left untouched -->
    <httpErrors existingResponse="PassThrough" />

    <!--
      You can control how Node is hosted within IIS using the following options:
        * watchedFiles: semi-colon separated list of files that will be watched for changes to restart the server
        * node_env: will be propagated to node as NODE_ENV environment variable
        * debuggingEnabled - controls whether the built-in debugger is enabled

      See https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/web.config for a full list of options
    -->
    <!--<iisnode watchedFiles="web.config;*.js"/>-->
  </system.webServer>
</configuration>

```

**Comment by ramijarrar** [comment]
What do your application settings look like? Are you trying to use SSL at all (e.g in your ROOT_URL)?

If there are any errors in the log stream (Kudu > Tools > Log Stream) that would be really helpful.

**Comment by SammyIsra** [comment]
I had an error on my ROOT_URL. I found that out via Kudu, thank you.
