### ISSUE TITLE
npm ERR! Failed at the bcrypt@0.8.7 install script.

### ISSUE THREAD

**Issue by ramijarrar** [fractal-code/meteor-azure#50]
Moved from https://github.com/fractal-code/meteor-azure/issues/43#issuecomment-357467317

> Hi! Sorry for opening this thread again, but I'm getting this error. Below is the output
>
> `` meteor-azure --settings settings-development.json -w web.config -d
debug: check Meteor is installed
debug: check for incompatible 'force-ssl' package
debug: check current Meteor release >= 1.4
info: Validating settings file
debug: check valid json exists
debug: check data follows schema
debug: dr-contact-lens-dev: configure kudu api
info: Validating Kudu connection
info: dr-contact-lens-dev: Authenticating with interactive login...
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code FMMHG6ZA3 to authenticate.
debug: dr-contact-lens-dev: completed Azure authentication
info: dr-contact-lens-dev: Updating Azure application settings
debug: dr-contact-lens-dev: retrieve existing values
debug: dr-contact-lens-dev: set environment variables
debug: dr-contact-lens-dev: set Meteor settings
debug: dr-contact-lens-dev: set Kudu deployment settings
debug: dr-contact-lens-dev: set Node to v8.8.1
debug: dr-contact-lens-dev: set NPM to v5.4.2
debug: dr-contact-lens-dev: serialise values
debug: dr-contact-lens-dev: push new settings
info: Compiling application bundle
debug: generate meteor build
debug: add custom web config
debug: checking for broken symlinks
debug: create tarball
info: dr-contact-lens-dev: Deploying bundle tarball
info: dr-contact-lens-dev: Running server initialisation
info: dr-contact-lens-dev: Polling server status...
load: 2.10 cmd: node 20372 waiting 16.77u 2.64s
debug: dr-contact-lens-dev: Retrieving Kudu deployment log...
debug: Command: bash script.sh
debug: meteor-azure: Now using NVM v1.1.4
debug: meteor-azure: Setting Node version
debug: Version 8.8.1 is already installed.
debug: meteor-azure: Now using Node v8.8.1 (32-bit)
debug: meteor-azure: Now using NPM v5.4.2
debug: meteor-azure: Unpacking bundle
debug: meteor-azure: Setting Node runtime
debug: meteor-azure: Enabling IISNode logging
debug: meteor-azure: Installing NPM dependencies
debug: /tmp/8d55ac83e1946d6/bundle/programs/server /tmp/8d55ac83e1946d6
debug:
debug: > fibers@2.0.0 install D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\node_modules\fibers
debug: > node build.js || nodejs build.js
debug:
debug: win32-ia32-57 exists; testing
debug: Binary is fine; exiting
debug:
debug: > meteor-dev-bundle@0.0.0 install D:\local\Temp\8d55ac83e1946d6\bundle\programs\server
debug: > node npm-rebuild.js
debug:
debug: npm WARN saveError EPERM: operation not permitted, rename 'D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm-shrinkwrap.json.4002820371' -> 'D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm-shrinkwrap.json'
debug: added 124 packages in 14.932s
debug: npm WARN meteor-dev-bundle@0.0.0 No description
debug: npm WARN meteor-dev-bundle@0.0.0 No repository field.
debug: npm WARN meteor-dev-bundle@0.0.0 No license field.
debug:
debug: /tmp/8d55ac83e1946d6
debug: meteor-azure: Rebuilding NPM dependencies
debug: /tmp/8d55ac83e1946d6/bundle/programs/server/npm /tmp/8d55ac83e1946d6
debug:
debug: > bcrypt@0.8.7 install D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm\node_modules\bcrypt
debug: > node-gyp rebuild
debug:
debug:
debug: D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm\node_modules\bcrypt>if not defined npm_config_node_gyp (node "D:\home\meteor-azure\nvm\v8.8.1\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "" rebuild )
debug: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
debug: D:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
debug: blowfish.cc
debug: bcrypt.cc
debug: bcrypt_node.cc
debug: win_delay_load_hook.cc
debug: ..\src\blowfish.cc : fatal error C1902: Program database manager mismatch; please check your installation [D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
debug: ..\src\bcrypt.cc : fatal error C1902: Program database manager mismatch; please check your installation [D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
debug: ..\src\bcrypt_node.cc : fatal error C1902: Program database manager mismatch; please check your installation [D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
debug: D:\home\meteor-azure\nvm\v8.8.1\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C1902: Program database manager mismatch; please check your installation [D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
debug: gyp ERR! build error
debug: gyp ERR! stack Error: msbuild failed with exit code: 1
debug: gyp ERR! stack at ChildProcess.onExit (D:\home\meteor-azure\nvm\v8.8.1\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
debug: gyp ERR! stack at emitTwo (events.js:125:13)
debug: gyp ERR! stack at ChildProcess.emit (events.js:213:7)
debug: gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
debug: gyp ERR! System Windows_NT 10.0.14393
debug: gyp ERR! command "D:\home\meteor-azure\nvm\v8.8.1\node.exe" "D:\home\meteor-azure\nvm\v8.8.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
debug: gyp ERR! cwd D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm\node_modules\bcrypt
debug: gyp ERR! node -v v8.8.1
debug: gyp ERR! node-gyp -v v3.6.2
debug: gyp ERR! not ok
debug: npm ERR! code ELIFECYCLE
debug: npm ERR! errno 1
debug: npm ERR! bcrypt@0.8.7 install: node-gyp rebuild
debug: npm ERR! Exit status 1
debug: npm ERR!
debug: npm ERR! Failed at the bcrypt@0.8.7 install script.
debug: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
debug:
debug: npm ERR! A complete log of this run can be found in:
debug: npm ERR! D:\local\AppData\npm-cache_logs\2018-01-13T21_01_11_892Z-debug.log
debug: meteor-azure: Could not rebuild NPM dependencies
debug: npm WARN saveError EPERM: operation not permitted, rename 'D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm-shrinkwrap.json.4002820371' -> 'D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm-shrinkwrap.json'\r\nnpm WARN meteor-dev-bundle@0.0.0 No description\r\nnpm WARN meteor-dev-bundle@0.0.0 No repository field.\r\nnpm WARN meteor-dev-bundle@0.0.0 No license field.\r\n\r\ngyp ERR! build error \r\ngyp ERR! stack Error: msbuild failed with exit code: 1\r\ngyp ERR! stack at ChildProcess.onExit (D:\home\meteor-azure\nvm\v8.8.1\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)\r\ngyp ERR! stack at emitTwo (events.js:125:13)\r\ngyp ERR! stack at ChildProcess.emit (events.js:213:7)\r\ngyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)\r\ngyp ERR! System Windows_NT 10.0.14393\r\ngyp ERR! command "D:\home\meteor-azure\nvm\v8.8.1\node.exe" "D:\home\meteor-azure\nvm\v8.8.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"\r\ngyp ERR! cwd D:\local\Temp\8d55ac83e1946d6\bundle\programs\server\npm\node_modules\bcrypt\r\ngyp ERR! node -v v8.8.1\r\ngyp ERR! node-gyp -v v3.6.2\r\ngyp ERR! not ok \r\nnpm ERR! code ELIFECYCLE\r\nnpm ERR! errno 1\r\nnpm ERR! bcrypt@0.8.7 install: node-gyp rebuild\r\nnpm ERR! Exit status 1\r\nnpm ERR! \r\nnpm ERR! Failed at the bcrypt@0.8.7 install script.\r\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR! D:\local\AppData\npm-cache_logs\2018-01-13T21_01_11_892Z-debug.log\r\nmeteor-azure: Could not rebuild NPM dependencies\r\nD:\Program Files (x86)\SiteExtensions\Kudu\70.10102.3204\bin\Scripts\starter.cmd bash script.sh
error: dr-contact-lens-dev: Failed to complete server initialisation ``
>
> Could you help me?
>
> Thanks!

**Comment by ramijarrar** [comment]
You version of bcrypt isn't compatible with Node v8 (see https://github.com/kelektiv/node.bcrypt.js/pull/527), please update the package to v1.0.3 and try again.

**Comment by dimadev01** [comment]
Hi @ramijarrar, thanks for the quick reply, and for orientating me. I've done what you said, and that problems disappeared. But now when I deploy I get this:

...
debug:   meteor-azure: Installing NPM dependencies
debug:   /tmp/8d55b72f1fdac1c/bundle/programs/server /tmp/8d55b72f1fdac1c
debug:    
debug:   > fibers@2.0.0 install D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\node_modules\fibers
debug:   > node build.js || nodejs build.js
debug:    
debug:   `win32-ia32-57` exists; testing
debug:   Binary is fine; exiting
debug:    
debug:   > meteor-dev-bundle@0.0.0 install D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server
debug:   > node npm-rebuild.js
debug:    
debug:   npm WARN saveError EPERM: operation not permitted, rename 'D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm-shrinkwrap.json.1489933515' -> 'D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm-shrinkwrap.json'
debug:   added 124 packages in 18.953s
debug:   npm WARN meteor-dev-bundle@0.0.0 No description
debug:   npm WARN meteor-dev-bundle@0.0.0 No repository field.
debug:   npm WARN meteor-dev-bundle@0.0.0 No license field.
debug:    
debug:   /tmp/8d55b72f1fdac1c
debug:   meteor-azure: Rebuilding NPM dependencies
debug:   /tmp/8d55b72f1fdac1c/bundle/programs/server/npm /tmp/8d55b72f1fdac1c
debug:    
debug:   > bcrypt@1.0.3 install D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm\node_modules\bcrypt
debug:   > node-pre-gyp install --fallback-to-build
debug:    
debug:   [bcrypt] Success: "D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm\node_modules\bcrypt\lib\binding\bcrypt_lib.node" is installed via remote
debug:    
debug:   > node-expat@2.3.16 install D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm\node_modules\node-expat
debug:   > node-gyp rebuild
debug:    
debug:    
debug:   D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm\node_modules\node-expat>if not defined npm_config_node_gyp (node "D:\home\meteor-azure\nvm\v8.8.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
debug:   Warning: Missing input files:
debug:   D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm\node_modules\node-expat\build\deps\libexpat\..\..\..\deps\libexpat\version.c
debug:   Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
debug:   D:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm\node_modules\node-expat\build\deps\libexpat\expat.vcxproj]
debug:     xmlparse.c
debug:     xmltok.c
debug:     xmlrole.c
debug:   ..\..\..\deps\libexpat\lib\xmlparse.c : fatal error C1902: Program database manager mismatch; please check your installation [D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm\node_modules\node-expat\build\deps\libexpat\expat.vcxproj]
debug:   ..\..\..\deps\libexpat\lib\xmltok.c : fatal error C1902: Program database manager mismatch; please check your installation [D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm\node_modules\node-expat\build\deps\libexpat\expat.vcxproj]
debug:   ..\..\..\deps\libexpat\lib\xmlrole.c : fatal error C1902: Program database manager mismatch; please check your installation [D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm\node_modules\node-expat\build\deps\libexpat\expat.vcxproj]
debug:   gyp ERR! build error 
debug:   gyp ERR! stack Error: `msbuild` failed with exit code: 1
debug:   gyp ERR! stack     at ChildProcess.onExit (D:\home\meteor-azure\nvm\v8.8.1\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
debug:   gyp ERR! stack     at emitTwo (events.js:125:13)
debug:   gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
debug:   gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
debug:   gyp ERR! System Windows_NT 10.0.14393
debug:   gyp ERR! command "D:\\home\\meteor-azure\\nvm\\v8.8.1\\node.exe" "D:\\home\\meteor-azure\\nvm\\v8.8.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
debug:   gyp ERR! cwd D:\local\Temp\8d55b72f1fdac1c\bundle\programs\server\npm\node_modules\node-expat
debug:   gyp ERR! node -v v8.8.1
debug:   gyp ERR! node-gyp -v v3.6.2
debug:   gyp ERR! not ok 
debug:   npm ERR! code ELIFECYCLE
debug:   npm ERR! errno 1
debug:   npm ERR! node-expat@2.3.16 install: `node-gyp rebuild`
debug:   npm ERR! Exit status 1
debug:   npm ERR! 
debug:   npm ERR! Failed at the node-expat@2.3.16 install script.
debug:   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
debug:    
debug:   npm ERR! A complete log of this run can be found in:
debug:   npm ERR!     D:\local\AppData\npm-cache\_logs\2018-01-14T17_23_43_583Z-debug.log
debug:   meteor-azure: Could not rebuild NPM dependencies
debug:   npm WARN saveError EPERM: operation not permitted, rename
...

I don't know exactly if it's a problem of `node-expat`, but I wasn't able to find a solution!

Thanks!!

**Comment by ramijarrar** [comment]
Are you using ``node-expat`` directly or via another package?

**Comment by dimadev01** [comment]
I've done a `npm ls` inside my project and `node-expat` is only being used by `xml2json` as far as I understand:

<img width="977" alt="screen shot 2018-01-14 at 14 48 25" src="https://user-images.githubusercontent.com/7450379/34918919-05d2fa42-f93a-11e7-8da5-1203c7d3e7f4.png">

 Thanks!

**Comment by ramijarrar** [comment]
There are many known issues with compiling node-expat binaries on Windows/later versions of Node (see https://github.com/buglabs/node-xml2json/issues/130, https://github.com/astro/node-expat/issues/184, https://github.com/astro/node-expat/issues/162) - given the lack of activity on the project, I doubt there will will be a fix soon.

I would suggest switching to a better maintained/more portable XML to JSON converter such as [xml-js](https://github.com/nashwaan/xml-js) or [node-xml2js](https://github.com/Leonidas-from-XIV/node-xml2js) - the APIs are fairly similar so it shouldn't be too difficult.

**Comment by dimadev01** [comment]
I understand! And once again @ramijarrar, thanks for your help! I'm glad there are people like you!

Best to you!

**Comment by ramijarrar** [comment]
No problem! Closing this for now, please let me know if you have any further issues.
