### ISSUE TITLE
"force-ssl" package is not supported

### ISSUE THREAD

**Issue by dpdonohue** [fractal-code/meteor-azure#53]
Hi!
I get this error
````
> meteor-azure --settings packages/example-plugin/configs/settings.example.json
> error:   The "force-ssl" package is not supported. Please read the docs to configure an HTTPS redirect in your web config.
```` 

- Operating system
macOS High Sierra v 10.13.3

- Meteor version
Meteor 1.6.0.1

- Package version (run `meteor-azure -v`)
v2.1.0-rc.3

**Comment by ramijarrar** [comment]
You need to remove the force-ssl package from your app. If you want to redirect users to HTTPS it needs to be configured in your web config (see relevant docs [here](http://meteor-azure.readthedocs.io/en/latest/configuration.html#setup-https-redirect)).
