### ISSUE TITLE
How to configure logging?

### ISSUE THREAD

**Issue by awatson1978** [fractal-code/meteor-azure#54]
Hello.  
Quick question:  What's the recommended way to set up logging with a meteor-azure instance?  

I can't seem to find the Meteor/Node server logs in Kudu, Activity Log, Application Insights, Diagnostic logs, Log stream, or anywhere else I look.

**Comment by ramijarrar** [comment]
The Meteor/Node logs are configured out of the box to go to the "D:\home\LogFiles\Application" directory, which can be viewed with the Kudu Diagnostics Console. You can bookmark the following link for easy access: "https://<YOUR_SITE_NAME>.scm.azurewebsites.net/api/vfs/LogFiles/Application/index.html"

<img width="894" alt="screen shot 2018-04-15 at 8 11 46 pm" src="https://user-images.githubusercontent.com/9661116/38777335-86ed32e0-40e9-11e8-9046-f5aa1019e98c.png">

If you want to you use Log Stream / view the raw IIS server logs this needs to be enabled in the Azure portal - more information on that [here](https://docs.microsoft.com/en-us/azure/app-service/web-sites-enable-diagnostic-log).

Let me know if any of the above is unclear / does not work as described. If you're running across multiple regions, you may find it easier to configure an external log management service (we are using Winston/Papertail in production).
