### ISSUE TITLE
Which OS to pick for azure web app

### ISSUE THREAD

**Issue by WayneUong** [fractal-code/meteor-azure#58]
Azure now lets you pick between Windows, Linux and Docker for the web app OS:
- Windows: has websockets option but no nodejs option
- Linux: has nodejs but no websockets option
- Docker: no nodejs, no websockets

I'd like to use Linux, but having no websockets toggle worries me. Which OS should I pick? Thank you.

**Comment by andynel** [comment]
for me only the windows deploy worked without any issues (didn't try Docker though)

**Comment by ramijarrar** [comment]
This tool is written to handle Windows deployments only (as noted in the Getting started tutorial).

@WayneUong Websockets should be enabled by default on Linux App Service so not sure what you are referring to?
