### ISSUE TITLE
Cannot install Meteor v1.4.1.1

### ISSUE THREAD

**Issue by jnes92** [fractal-code/meteor-azure#6]
Hey, i just used your git to make a test Project and deploy it to Azure.
It worked absolutely fine and setup was very easy.

But now I want to deploy my real project to azure, it was done with Meteor1.4.1.1 (now Version 1.4.1.3 is available, but I cant update). 

Can you tell me where you got that link for installing meteor ? 
# curl -L -o meteor.tar.gz "https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_32"

This command will always download the latest release and after I configured continous deployment my repo always fails.

As a result my log looks like that: 

`2016-10-25T12:58:55.9361803Z,Sorry&comma; this project uses Meteor 1.4.1.1&comma; which is not installed and could,,1
    2016-10-25T12:58:55.9519454Z,not be downloaded. Please check to make sure that you are online.,,1
    2016-10-25T12:58:56.1237034Z,cp: cannot create regular file 'D:\local\LocalAppData\meteor-azure\bundle': No such file or directory,,1
    2016-10-25T12:58:56.1392866Z,Handling node.js deployment.,,0
    2016-10-25T12:58:57.1995287Z,KuduSync.NET from: 'D:\local\LocalAppData\meteor-azure\bundle' to: 'D:\home\site\wwwroot',,0
    2016-10-25T12:58:57.1995287Z,Error: Could not find a part of the path 'D:\local\LocalAppData\meteor-azure\bundle'.,,1
    2016-10-25T12:58:57.2151088Z,An error has occurred during web site deployment.,,0
    2016-10-25T12:58:57.2151088Z,Kudu Sync failed,,0
`

**Comment by ramijarrar** [comment]
The process is based on the recommended steps for command-line installation  which are documented by MDG [here](https://github.com/meteor/docs/blob/version-NEXT/long-form/alternate-windows-installation.md). 

It definitely shouldn't matter which version of Meteor you are using - I think the issue you're having may be CDN related and I recall there were some improvements for this in 1.4.2 (now an officially recommended release)

Can you elaborate more on why you are unable to update your release and redeploy?

**Comment by ramijarrar** [comment]
That line is based on the steps provided by MDG for command line installation - the build tool is capable of automatically selecting the version relevant to your app so there is reason to modify this.

From what I can tell it looks like there is some trouble (most likely CDN related: meteor/meteor#6960) which is preventing it from downloading the 1.4.1.1 release.

The easiest way to solve this would probably just be to update Meteor and redeploy.

**Comment by jnes92** [comment]
thanks a lot @ramijarrar !
I updated Meteor locally and redelpoyed this new Version !

So if i got you right, the build tool will be always install the current version from my project (and this time i was unlucky?).

Thanks for the fast response !!

Edit: Tested again today now everything works as it should 
Meteor 1.4.2 was released, but it used the right version from my project :)

So Closing now.

**Comment by ramijarrar** [comment]
That is correct (just like with running the app locally)
