### ISSUE TITLE
Deploy from Github directly

### ISSUE THREAD

**Issue by mohkamfer** [fractal-code/meteor-azure#62]
I have a large Meteor project that I wanted to deploy on an Azure Web App, but everything is already uploaded to GitHub, so I wonder if I could use meteor-azure to deploy from GitHub directly instead of compressing and uploading the whole project again.

Sorry for making this an Issue, but I couldn't find a proper place and way to reach everyone on the repository.

**Comment by ramijarrar** [comment]
See https://github.com/fractal-code/meteor-azure/issues/49 - you can configure a CI tool (e.g CircleCI or Codeship) to automate the deploy process from a Git push.

**Comment by mohkamfer** [comment]
Oh that issue certainly popped up while I was typing the title, but I thought it was automating the process when I push from my machine.

So to be correct, the tool itself will deploy on azure, and not me?
Is it safe to put the app credentials on it?

EDIT: I guess #49 's title could reflect my same issue a bit more clearly?
Like instead of 'Run meteor-azure after GitHub push' it could be 'Use GitHub for meteor-azure' since I was completely tricked by the title.

**Comment by ramijarrar** [comment]
Yes - you can configure the CI server to clone from Github and proceed to install Meteor, NPM deps and push to Azure without any manual action on your part.

Managing credentials will depend on the tool you select (e.g for CircleCI see https://circleci.com/docs/2.0/env-vars/)

**Comment by ramijarrar** [comment]
Closing this thread - feel free to reopen or create a new issue for further questions/issues.
