### ISSUE TITLE
[QUESTION] Updating already published build on azure

### ISSUE THREAD

**Issue by simplecommerce** [fractal-code/meteor-azure#66]
Great work by the way, I tried it yesterday for the first time and it worked flawlessly.

My only question was this.

After the initial execution of the command.
If I do changes to my app and want to update it again, what is the best way?

Should I simple re-execute the same code I did for the initial build?

What do you suggest?

Thanks!

**Comment by ramijarrar** [comment]
Yes - generally you rerun the build to push new changes to your app.

For urgent patches you can also edit files in place with the App Service editor - have a read of this article for more details: https://social.technet.microsoft.com/wiki/contents/articles/36467.understanding-the-azure-app-service-editor.aspx
