### ISSUE TITLE
Error with interactive login

### ISSUE THREAD

**Issue by ManuelDeLeon** [fractal-code/meteor-azure#71]
- Operating system: Windows and Linux
- Meteor version: 1.8.1
- Package version: 2.1.1

When I tried to deploy a test website, I had to do the interactive login as usual but it failed at the end of the process:
```
	2019-06-10T18:49:26.9501456Z,/tmp/8d6edd3affdebea,,0
	2019-06-10T18:49:26.9657879Z,meteor-azure: Syncing bundle,,0
	2019-06-10T18:51:11.4160155Z,Thread was being aborted.,,1
	2019-06-10T18:51:11.4160155Z,Thread was being aborted.,,2
```
I tried to deploy again but now I can't get the interactive login to work:
```
info:    Targetting 32-bit Node architecture
debug:   check Meteor is installed
debug:   check for incompatible 'force-ssl' package
debug:   check current Meteor release >= 1.4
info:    Validating settings file (settings-prod.json)
debug:   check valid json exists
debug:   check data follows schema
debug:   weebirthday: configure kudu api
info:    Validating Kudu connection (settings-prod.json)
info:    weebirthday: Authenticating with interactive login...
error:   weebirthday: Get Device Code  request returned http error: 400 and server response: 
{
  "error":"invalid_request",
  "error_description":"AADSTS220050: The specified encryption key version override 23 was not found in the list of keys.",
  "error_codes":[220050],
  "timestamp":"2019-06-10 22:20:38Z",
  "trace_id":"e9f5545f-39ed-47b0-91d6-c1d3aabef600",
  "correlation_id":"6cf01d20-efe8-4653-8f26-d60aa7c68b74"
}
```
For what it's worth I can login via `az login`.

What can I try?

**Comment by ramijarrar** [comment]
I saw a very similar error on MSDN forums today with the PS API (see [here](https://social.msdn.microsoft.com/Forums/en-US/2c3e80d4-d26c-4ba4-8c4f-653d1ea5327f/cant-connect-to-azure-with-powershell-6?forum=WindowsAzureAD)) - could be an MS backend issue or just inconsistent state. Have you tried clearing the browser cache / cookies to see if that helps?

The interactive logins are implemented with the Azure Node SDK, so wouldn't really share any state with ``az login`` through the CLI.

Also, the build failure message you got initially "Thread was being aborted" would mean that the server initialisation was interrupted, usually by a restart or application setting change (we also trigger this intentionally with a new deploy).

**Comment by ManuelDeLeon** [comment]
Thanks. Maybe it was something at MS. I just tried again and it passed the login stage. Hopefully it's able to fully deploy the site :) 
I'll close this issue tho.

Thanks again.
