### ISSUE TITLE
force-ssl

### ISSUE THREAD

**Issue by michaelfp** [fractal-code/meteor-azure#75]
Hi! The documentation is not clear enough to help to execute the package. Where I placed the web.config? I put on my hosted app service but when I ran in windows cmd npm run deploy, always return error on force-ssl
> meteor-azure

info:    Targetting 32-bit Node architecture
error:   The "force-ssl" package is not supported. Please read the docs to configure an HTTPS redirect in your web config.
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by ramijarrar** [comment]
You need to point to the custom web config file in your deploy command:

```sh
meteor-azure --settings 'example/path/settings.json' --web-config 'example/path/web.config'
```

If you want to configure HTTPS redirect, remove the force-ssl package & add the rule to your web config. 

This is documented [here](https://meteor-azure.readthedocs.io/en/latest/configuration.html#custom-web-config) and there are [samples available](https://github.com/fractal-code/meteor-azure-web-config/tree/master/samples) to copy directly if you are new to IISNode.

Hope that helps.
