### ISSUE TITLE
 Error 500 when meteor app deployed on azure

### ISSUE THREAD

**Issue by nwabdou85** [fractal-code/meteor-azure#77]
Hy
I deployed my meteor app on azure but can't connect it  to my react native app. 
I did something lik that Meteor.connect('wss://XXXX.azurewebsites.net/websocket'), but does not work, knowing that it works perfectly with the same code deployed on heroku.
I think that all the options are corrects and the deployment has been well done.

this log from kudu
https://paste.ofcode.org/yuvww3zEKJTZJWUMbURiD3

Redeployed the code with - - architecture 64, same thing can't connect. 

Any help here please?

**Comment by nwabdou85** [comment]
@ramijarrar can you help here, please?

**Comment by ramijarrar** [comment]
Hi @nwabdou85 - can you try removing the Monti APM agent & redeploying?

Most likely this issue relates to  binary dependencies that aren't prebuilt & cannot be compiled in place on App Service (see comments in https://github.com/fractal-code/meteor-azure/issues/65 which is a very similar case).

**Comment by 55** [comment]
@nwabdou85 were you able to solve your issue?

**Comment by nwabdou85** [comment]
@ramijarrar  sorry for the reply, for now I use was; but if I remember, your suggestion was the key; 
@55 yes;
